import type { PresentationId } from "@/lib/protocol/types";
import type { WaterType } from "@/lib/protocol/vocab";

export type PresentationFamily = {
  id: PresentationId;
  label: string;
  water: WaterType | "both";
  job: string;
  mechanics: string[];
  system: Record<string, string>;
};

export const PRESENTATIONS: PresentationFamily[] = [
  {
    id: "dead_drift",
    label: "Dead drift",
    water: "flowing",
    job: "Allow a food-form imitation to move at or near current speed through a defined feeding lane.",
    mechanics: ["controlled depth", "minimal drag", "short-to-medium presentation lane", "occasional repositioning"],
    system: {
      depthControl: "high",
      sensitivity: "high",
      castingDistance: "short_to_moderate",
      lureWeightBand: "1/64–1/8 oz or unweighted fly",
      coverResistance: "low",
      lineVisibilityPreference: "low",
      retieFrequency: "moderate",
    },
  },
  {
    id: "tight_line_drift",
    label: "Tight-line drift",
    water: "flowing",
    job: "Keep a near-direct connection to a drifting imitation so depth and contact can be felt without a floating indicator.",
    mechanics: ["in-touch leader", "lead the drift", "detect ticks and pauses", "reset after each lane"],
    system: {
      depthControl: "high",
      sensitivity: "high",
      castingDistance: "short",
      lureWeightBand: "1/64–3/16 oz",
      coverResistance: "moderate",
      lineVisibilityPreference: "low",
      retieFrequency: "high",
    },
  },
  {
    id: "swing",
    label: "Swing",
    water: "flowing",
    job: "Let current carry a bait or fly across a lane so it broadens and lifts at the hang.",
    mechanics: ["downstream quartering", "controlled belly", "hang-down pause", "slow lift"],
    system: {
      depthControl: "moderate",
      sensitivity: "moderate",
      castingDistance: "moderate",
      lureWeightBand: "unweighted to 1/4 oz",
      coverResistance: "low",
      lineVisibilityPreference: "moderate",
      retieFrequency: "low",
    },
  },
  {
    id: "suspended_drift",
    label: "Suspended drift",
    water: "flowing",
    job: "Hold an imitation in the column, not on the bottom, while it moves with or slightly slower than the current.",
    mechanics: ["depth retention", "neutral or slow sink", "lane tracking", "minimal acceleration"],
    system: {
      depthControl: "high",
      sensitivity: "high",
      castingDistance: "moderate",
      lureWeightBand: "1/16–1/4 oz",
      coverResistance: "low",
      lineVisibilityPreference: "low",
      retieFrequency: "moderate",
    },
  },
  {
    id: "bottom_contact_drift",
    label: "Bottom-contact drift",
    water: "flowing",
    job: "Tick or crawl a food form along the substrate through a feeding lane without snagging constantly.",
    mechanics: ["feel the bottom", "short hops", "reset after hang", "weight just enough"],
    system: {
      depthControl: "high",
      sensitivity: "high",
      castingDistance: "moderate",
      lureWeightBand: "1/8–3/8 oz",
      coverResistance: "moderate",
      lineVisibilityPreference: "low",
      retieFrequency: "moderate",
    },
  },
  {
    id: "cross_current_retrieve",
    label: "Cross-current retrieve",
    water: "flowing",
    job: "Represent mobile prey crossing or holding near a current boundary.",
    mechanics: ["horizontal travel", "intermittent pause", "depth retention", "controlled acceleration"],
    system: {
      depthControl: "moderate",
      sensitivity: "moderate",
      castingDistance: "moderate",
      lureWeightBand: "1/8–3/8 oz",
      coverResistance: "moderate",
      lineVisibilityPreference: "low",
      retieFrequency: "moderate",
    },
  },
  {
    id: "upstream_retrieve",
    label: "Upstream retrieve",
    water: "flowing",
    job: "Bring a bait back against current so it tracks a seam or bank the fish is already facing.",
    mechanics: ["cast down-and-across or down", "retrieve into the lane", "keep contact", "vary cadence at the head"],
    system: {
      depthControl: "moderate",
      sensitivity: "moderate",
      castingDistance: "moderate",
      lureWeightBand: "1/8–1/2 oz",
      coverResistance: "moderate",
      lineVisibilityPreference: "moderate",
      retieFrequency: "moderate",
    },
  },
  {
    id: "downstream_retrieve",
    label: "Downstream retrieve",
    water: "flowing",
    job: "Move a bait with the current, then add just enough speed to give it a swimming job.",
    mechanics: ["cast upstream", "recover slack", "match or slightly beat current", "pause in pockets"],
    system: {
      depthControl: "moderate",
      sensitivity: "moderate",
      castingDistance: "moderate",
      lureWeightBand: "1/16–3/8 oz",
      coverResistance: "low",
      lineVisibilityPreference: "low",
      retieFrequency: "moderate",
    },
  },
  {
    id: "pulse_jig",
    label: "Pulse / jig",
    water: "flowing",
    job: "Lift and drop a compact bait so it occupies a pocket, seam, or head without leaving the water column.",
    mechanics: ["short lift", "controlled drop", "stay in the pocket", "repeat on the same piece"],
    system: {
      depthControl: "high",
      sensitivity: "high",
      castingDistance: "short_to_moderate",
      lureWeightBand: "1/8–3/8 oz",
      coverResistance: "moderate",
      lineVisibilityPreference: "low",
      retieFrequency: "high",
    },
  },
  {
    id: "surface_drift",
    label: "Surface drift",
    water: "flowing",
    job: "Present a floating food form in a feeding lane with as little drag as the water allows.",
    mechanics: ["slack management", "reach or mend", "dead or micro-twitch", "leave it in the lane"],
    system: {
      depthControl: "surface",
      sensitivity: "moderate",
      castingDistance: "short_to_moderate",
      lureWeightBand: "unweighted",
      coverResistance: "low",
      lineVisibilityPreference: "low",
      retieFrequency: "moderate",
    },
  },
  {
    id: "wake_skate",
    label: "Wake / skate",
    water: "flowing",
    job: "Create a visible surface disturbance that suggests a struggling or fleeing food form.",
    mechanics: ["across or down-and-across", "keep it on top", "pulse the wake", "cover water"],
    system: {
      depthControl: "surface",
      sensitivity: "low",
      castingDistance: "moderate",
      lureWeightBand: "unweighted to 1/4 oz",
      coverResistance: "low",
      lineVisibilityPreference: "moderate",
      retieFrequency: "low",
    },
  },
  {
    id: "stationary_bait",
    label: "Stationary bait",
    water: "flowing",
    job: "Hold a scent or food form in one feeding station and wait for a fish to move to it.",
    mechanics: ["anchor the presentation", "keep bait in the pocket", "detect takes without sweeping", "refresh often"],
    system: {
      depthControl: "high",
      sensitivity: "moderate",
      castingDistance: "short",
      lureWeightBand: "1/4–1 oz",
      coverResistance: "high",
      lineVisibilityPreference: "moderate",
      retieFrequency: "high",
    },
  },
  {
    id: "horizontal_retrieve",
    label: "Horizontal retrieve",
    water: "stillwater",
    job: "Move a swimming bait through a chosen depth band along structure or open water.",
    mechanics: ["count down", "steady or pulsing retrieve", "keep the band", "cover the edge"],
    system: {
      depthControl: "moderate",
      sensitivity: "moderate",
      castingDistance: "moderate_to_long",
      lureWeightBand: "1/8–1/2 oz",
      coverResistance: "moderate",
      lineVisibilityPreference: "low",
      retieFrequency: "low",
    },
  },
  {
    id: "stop_and_go",
    label: "Stop-and-go",
    water: "stillwater",
    job: "Imitate injured or hesitating prey by mixing travel with pauses that hold the bait in the strike zone.",
    mechanics: ["travel", "pause", "keep depth on the pause", "restart without jumping the band"],
    system: {
      depthControl: "high",
      sensitivity: "high",
      castingDistance: "moderate",
      lureWeightBand: "1/8–3/8 oz",
      coverResistance: "moderate",
      lineVisibilityPreference: "low",
      retieFrequency: "moderate",
    },
  },
  {
    id: "suspend_pause",
    label: "Suspend / pause",
    water: "stillwater",
    job: "Leave a neutrally buoyant bait hanging in place where fish are already holding.",
    mechanics: ["reach the band", "long pause", "tiny pulse only if needed", "do not leave the zone"],
    system: {
      depthControl: "high",
      sensitivity: "high",
      castingDistance: "moderate",
      lureWeightBand: "1/8–3/8 oz suspending",
      coverResistance: "low",
      lineVisibilityPreference: "low",
      retieFrequency: "low",
    },
  },
  {
    id: "vertical_jig",
    label: "Vertical jig",
    water: "stillwater",
    job: "Work a compact bait up and down through a marked depth, basin, or timber pocket.",
    mechanics: ["stay over the target", "measured lift", "controlled drop", "watch slack"],
    system: {
      depthControl: "high",
      sensitivity: "high",
      castingDistance: "vertical",
      lureWeightBand: "1/8–3/4 oz",
      coverResistance: "moderate",
      lineVisibilityPreference: "low",
      retieFrequency: "moderate",
    },
  },
  {
    id: "bottom_contact",
    label: "Bottom contact",
    water: "stillwater",
    job: "Keep a bait on or just above the substrate along a break, flat, or inside a weed edge.",
    mechanics: ["feel bottom", "drag or hop", "pause on the break", "stay in contact"],
    system: {
      depthControl: "high",
      sensitivity: "high",
      castingDistance: "moderate",
      lureWeightBand: "1/8–1/2 oz",
      coverResistance: "high",
      lineVisibilityPreference: "low",
      retieFrequency: "high",
    },
  },
  {
    id: "slow_drag",
    label: "Slow drag",
    water: "stillwater",
    job: "Move a bait along the bottom slowly enough that it stays in the feeding layer of inactive fish.",
    mechanics: ["continuous contact", "very slow travel", "pause at changes in bottom", "do not hop out of the zone"],
    system: {
      depthControl: "high",
      sensitivity: "high",
      castingDistance: "moderate",
      lureWeightBand: "1/8–3/8 oz",
      coverResistance: "moderate",
      lineVisibilityPreference: "low",
      retieFrequency: "moderate",
    },
  },
  {
    id: "drop_presentation",
    label: "Drop presentation",
    water: "stillwater",
    job: "Let a bait fall on a controlled line into cover, along a wall, or through a hole in vegetation.",
    mechanics: ["place then fall", "watch the line", "hold at depth", "short hop only after the fall"],
    system: {
      depthControl: "high",
      sensitivity: "high",
      castingDistance: "short",
      lureWeightBand: "1/16–3/8 oz",
      coverResistance: "high",
      lineVisibilityPreference: "low",
      retieFrequency: "high",
    },
  },
  {
    id: "surface_retrieve",
    label: "Surface retrieve",
    water: "stillwater",
    job: "Work a floating bait across shade, weed edges, or low-light shallows.",
    mechanics: ["walk, pop, or crawl", "pause in holes", "keep it on top", "cover the edge"],
    system: {
      depthControl: "surface",
      sensitivity: "low",
      castingDistance: "moderate",
      lureWeightBand: "1/4–3/4 oz",
      coverResistance: "moderate",
      lineVisibilityPreference: "moderate",
      retieFrequency: "low",
    },
  },
  {
    id: "subsurface_slow_roll",
    label: "Subsurface slow-roll",
    water: "stillwater",
    job: "Roll a bait just under the surface or just over the weed tops without breaking them.",
    mechanics: ["barely subsurface", "steady roll", "tick the tops", "speed just enough to stay up"],
    system: {
      depthControl: "moderate",
      sensitivity: "moderate",
      castingDistance: "moderate_to_long",
      lureWeightBand: "1/4–3/4 oz",
      coverResistance: "high",
      lineVisibilityPreference: "moderate",
      retieFrequency: "moderate",
    },
  },
  {
    id: "suspended_stationary",
    label: "Suspended stationary",
    water: "stillwater",
    job: "Park a live or scent bait in the column where fish are already using a depth band.",
    mechanics: ["find the band", "hold it", "minimal motion", "refresh bait"],
    system: {
      depthControl: "high",
      sensitivity: "moderate",
      castingDistance: "short_to_vertical",
      lureWeightBand: "sinker as needed",
      coverResistance: "low",
      lineVisibilityPreference: "low",
      retieFrequency: "moderate",
    },
  },
  {
    id: "trolling",
    label: "Trolling",
    water: "stillwater",
    job: "Cover a depth contour or basin at a controlled speed to intercept mobile fish.",
    mechanics: ["speed control", "depth control", "follow the contour", "turn to change action"],
    system: {
      depthControl: "high",
      sensitivity: "low",
      castingDistance: "boat",
      lureWeightBand: "varies with speed and depth",
      coverResistance: "low",
      lineVisibilityPreference: "moderate",
      retieFrequency: "low",
    },
  },
  {
    id: "live_natural_bait_suspension",
    label: "Live / natural bait suspension",
    water: "both",
    job: "Present a natural food form with enough life or scent to hold in a station without looking mechanical.",
    mechanics: ["keep it alive or fresh", "match the holding depth", "minimize hardware bulk", "detect without pulling it away"],
    system: {
      depthControl: "high",
      sensitivity: "high",
      castingDistance: "short_to_moderate",
      lureWeightBand: "as light as conditions allow",
      coverResistance: "moderate",
      lineVisibilityPreference: "low",
      retieFrequency: "high",
    },
  },
];

export const PRESENTATION_BY_ID = Object.fromEntries(
  PRESENTATIONS.map((p) => [p.id, p]),
) as Record<PresentationId, PresentationFamily>;
