import type { SpeciesRecord } from "../protocol/types.ts";

const SRC = {
  agency: "agency" as const,
  peer: "peer_reviewed" as const,
  syn: "synthesis" as const,
};

/**
 * Reviewed expansion batch 04 — 15 high-value North American gaps.
 *
 * The batch deliberately separates life-history forms that must not collapse
 * onto existing records (anadromous sockeye vs kokanee; landlocked Atlantic
 * salmon vs wild sea-run Atlantic salmon). Salmon returning to freshwater are
 * never described as feeding simply because a presentation family is emitted;
 * migration/interception families represent mechanics, not a feeding claim.
 */
export const SPECIES_EXPANSION_04: SpeciesRecord[] = [
  {
    id: "oncorhynchus_nerka_anadromous",
    scientificName: "Oncorhynchus nerka",
    commonNames: ["Sockeye salmon", "Red salmon"],
    group: "trout_salmon",
    targetStatus: "regulated_context",
    nativeContext: "Anadromous Pacific salmon native to the North Pacific. This record is explicitly separate from landlocked kokanee.",
    thermal: { preferredF: [42, 55], activeF: [38, 60], coldEdgeF: 34, warmEdgeF: 65 },
    spawning: {
      seasons: ["summer", "late_summer", "fall"],
      note: "Adults return through freshwater toward lake/tributary spawning systems in summer and fall. Spawning reaches, staging concentrations, and ESA-listed populations are invalidators, never target layers.",
    },
    habitat: {
      waterTypes: ["flowing", "stillwater"],
      riverHolding: ["run", "current_break", "pool_head", "pool_tail", "tributary_mouth"],
      stillHolding: ["inlet", "outlet", "suspended_open", "drop_off"],
      currentPreference: "Migrating adults use river travel lanes, velocity relief, and lake/river transitions rather than establishing trout-like feeding lies.",
      depthTendency: "Freshwater adults may move through the column with migration stage, flow, light, and lake/river transition; juvenile lake residence is not an adult targeting proxy.",
      lightResponse: "Light can alter travel depth and visibility, but it does not convert freshwater migration into proof of feeding.",
    },
    forageClasses: ["zooplankton", "aquatic_insects", "small_forage_fish"],
    flowingPresentations: ["swing", "cross_current_retrieve", "downstream_retrieve", "pulse_jig"],
    stillPresentations: ["horizontal_retrieve", "suspend_pause", "vertical_jig"],
    exceptions: [
      "Freshwater returning adults are modeled as migration/interception context, not a claim that they are actively feeding.",
      "Snake River and Ozette Lake sockeye are federally protected ESUs; population status must be explicitly declared rather than inferred from a water name.",
      "Kokanee remains a separate landlocked record and the alias 'sockeye' must never resolve to kokanee after this record exists.",
    ],
    geographic: "North Pacific drainages from Alaska through the Pacific Northwest; population status ranges from large managed fisheries to ESA-listed ESUs.",
    sources: [
      { label: "NOAA Fisheries Sockeye Salmon species profile", class: SRC.agency },
      { label: "NOAA Fisheries Sockeye Salmon protected-ESU profile", class: SRC.agency },
    ],
    reviewedAt: "2026-08-27",
    nextReviewAt: "2026-11-27",
  },
  {
    id: "oncorhynchus_gorbuscha",
    scientificName: "Oncorhynchus gorbuscha",
    commonNames: ["Pink salmon", "Humpback salmon"],
    group: "trout_salmon",
    targetStatus: "regulated_context",
    nativeContext: "Anadromous Pacific salmon with an obligate two-year life cycle and rapid juvenile movement from gravel to estuary/ocean.",
    thermal: { preferredF: [44, 58], activeF: [38, 62], coldEdgeF: 34, warmEdgeF: 66 },
    spawning: {
      seasons: ["summer", "late_summer", "fall"],
      note: "Spawns from summer into fall. Returning adults stop feeding in freshwater; redds and concentrated spawning fish are excluded from target guidance.",
    },
    habitat: {
      waterTypes: ["flowing"],
      riverHolding: ["run", "pool_head", "pool_tail", "current_break", "tributary_mouth"],
      stillHolding: [],
      currentPreference: "Freshwater adults are migratory river fish; velocity relief and travel lanes matter more than resident feeding stations.",
      depthTendency: "Typically mid-column to lower-column during river migration, varying with flow, channel form, and light.",
      lightResponse: "Lower light can alter migration depth and visibility but is not evidence that returning adults have resumed feeding.",
    },
    forageClasses: ["aquatic_insects", "zooplankton", "small_forage_fish"],
    flowingPresentations: ["swing", "cross_current_retrieve", "downstream_retrieve", "pulse_jig"],
    stillPresentations: [],
    exceptions: [
      "ADF&G states that adults returning to freshwater stop eating; presentation output therefore describes interception/reaction mechanics only.",
      "The two-year life cycle creates strong odd/even-year population structure in many systems; abundance must not be inferred from habitat alone.",
    ],
    geographic: "North Pacific coastal drainages, especially Alaska and the Pacific Northwest; primarily lower/coastal river systems with some longer inland migrations.",
    sources: [
      { label: "Alaska Department of Fish and Game Pink Salmon species profile", class: SRC.agency },
    ],
    reviewedAt: "2026-08-27",
    nextReviewAt: "2026-11-27",
  },
  {
    id: "oncorhynchus_keta",
    scientificName: "Oncorhynchus keta",
    commonNames: ["Chum salmon", "Keta salmon"],
    group: "trout_salmon",
    targetStatus: "regulated_context",
    nativeContext: "Wide-ranging anadromous Pacific salmon; most juveniles move quickly from freshwater into estuarine and marine habitat.",
    thermal: { preferredF: [42, 56], activeF: [38, 60], coldEdgeF: 34, warmEdgeF: 64 },
    spawning: {
      seasons: ["late_summer", "fall", "late_fall", "winter"],
      note: "Spawning timing varies broadly by population from late summer into winter. Listed ESUs and spawning concentrations are conservation context, not target opportunities.",
    },
    habitat: {
      waterTypes: ["flowing"],
      riverHolding: ["run", "current_break", "pool_head", "pool_tail", "tributary_mouth"],
      stillHolding: [],
      currentPreference: "Returning adults use migration lanes and velocity relief in coastal rivers; the record does not convert spawning migration into a feeding model.",
      depthTendency: "Generally travels through mid and lower river columns with flow and channel depth rather than holding as a resident trout.",
      lightResponse: "Light and turbidity can alter visibility and travel depth; neither is a bite predictor.",
    },
    forageClasses: ["small_forage_fish", "crustaceans", "zooplankton"],
    flowingPresentations: ["swing", "cross_current_retrieve", "downstream_retrieve", "pulse_jig"],
    stillPresentations: [],
    exceptions: [
      "Hood Canal summer-run and Columbia River chum ESUs are federally threatened; population-level status must be explicitly declared.",
      "Adult freshwater presentation is migration/interception context, not proof of active feeding.",
    ],
    geographic: "North Pacific and Arctic-influenced coastal drainages; U.S. range extends throughout Alaska and south into the Pacific Northwest.",
    sources: [
      { label: "NOAA Fisheries Chum Salmon species profile", class: SRC.agency },
      { label: "NOAA Fisheries Chum Salmon protected-ESU profile", class: SRC.agency },
    ],
    reviewedAt: "2026-08-27",
    nextReviewAt: "2026-11-27",
  },
  {
    id: "salmo_salar_landlocked",
    scientificName: "Salmo salar (landlocked freshwater form)",
    commonNames: ["Landlocked Atlantic salmon", "Landlocked salmon", "Sebago salmon"],
    group: "trout_salmon",
    nativeContext: "Freshwater form of Atlantic salmon, native to a small number of northeastern lake/river systems and widely managed by stocking. Explicitly separate from wild sea-run Atlantic salmon.",
    thermal: { preferredF: [48, 60], activeF: [40, 64], coldEdgeF: 34, warmEdgeF: 68 },
    spawning: {
      seasons: ["fall", "late_fall"],
      note: "Wild fish spawn in lake inlets or outlets from mid-October through late November. Spawning runs are invalidators, not target layers.",
    },
    habitat: {
      waterTypes: ["stillwater", "flowing"],
      riverHolding: ["run", "seam", "pool_head", "pool_tail", "current_break"],
      stillHolding: ["suspended_open", "thermocline_edge", "inlet", "outlet", "drop_off", "basin"],
      currentPreference: "River fish use cold drift lanes and pools; lake fish are primarily pelagic and forage-linked rather than cover-bound.",
      depthTendency: "Often near surface in cool spring/fall conditions, then commonly descends into cold oxygenated water during summer stratification.",
      lightResponse: "Low light and broken surface conditions can support higher positioning; bright summer conditions reinforce depth in clear lakes.",
    },
    forageClasses: ["small_forage_fish", "aquatic_insects", "emerging_insects", "terrestrial_insects"],
    flowingPresentations: ["dead_drift", "swing", "cross_current_retrieve", "surface_drift"],
    stillPresentations: ["trolling", "horizontal_retrieve", "suspend_pause", "surface_retrieve", "vertical_jig"],
    exceptions: [
      "Maine identifies rainbow smelt as principal lake forage; absence of smelt or equivalent pelagic forage can materially change growth and positioning.",
      "Do not confuse this record with federally endangered wild Gulf of Maine sea-run Atlantic salmon.",
    ],
    geographic: "Northeastern North American cold lakes and connected rivers, with especially important native and managed fisheries in Maine and eastern Canada.",
    sources: [
      { label: "Maine Department of Inland Fisheries and Wildlife Landlocked Salmon species profile", class: SRC.agency },
      { label: "Maine landlocked Atlantic salmon management literature", class: SRC.agency },
    ],
    reviewedAt: "2026-08-27",
    nextReviewAt: "2026-11-27",
  },
  {
    id: "salvelinus_alpinus",
    scientificName: "Salvelinus alpinus",
    commonNames: ["Arctic char"],
    group: "trout_salmon",
    nativeContext: "Circumpolar coldwater char. This reviewed North American seed emphasizes the documented lake-resident Alaska form; anadromous Eurasian forms are outside this record.",
    thermal: { preferredF: [39, 50], activeF: [33, 56], coldEdgeF: 32, warmEdgeF: 60 },
    spawning: {
      seasons: ["late_summer", "fall"],
      note: "Alaska lake populations spawn over gravel/rubble shoals from August into October. Spawning shoals are not emitted as target locations.",
    },
    habitat: {
      waterTypes: ["stillwater"],
      riverHolding: [],
      stillHolding: ["basin", "drop_off", "rocky_shoreline", "submerged_hump", "thermocline_edge", "inlet"],
      currentPreference: "Reviewed here as a lake-resident fish; basin circulation and coldwater structure matter more than river current classes.",
      depthTendency: "Highly population- and season-dependent; can range from littoral/insect feeding to deep cold basin use, with larger fish often becoming more piscivorous.",
      lightResponse: "Clear water and bright conditions can reinforce deeper positioning; insect availability can pull smaller/feeding fish higher.",
    },
    forageClasses: ["zooplankton", "aquatic_insects", "emerging_insects", "crustaceans", "small_forage_fish", "larger_prey_fish"],
    flowingPresentations: [],
    stillPresentations: ["vertical_jig", "slow_drag", "drop_presentation", "horizontal_retrieve", "trolling", "surface_retrieve"],
    exceptions: [
      "Arctic char are exceptionally polymorphic among lakes; body size, diet, depth use, and color can differ substantially within the species.",
      "Dolly Varden and Arctic char are commonly confused; identification should be visually verified rather than inferred from geography alone.",
    ],
    geographic: "Circumpolar North America; Alaska populations documented by ADF&G are primarily cold lake residents.",
    sources: [
      { label: "Alaska Department of Fish and Game Arctic Char species profile", class: SRC.agency },
    ],
    reviewedAt: "2026-08-27",
    nextReviewAt: "2026-11-27",
  },
  {
    id: "salvelinus_malma",
    scientificName: "Salvelinus malma",
    commonNames: ["Dolly Varden"],
    group: "trout_salmon",
    nativeContext: "Pacific/arctic char with resident and sea-run forms; Alaska populations show strong regional and life-history variation.",
    thermal: { preferredF: [42, 55], activeF: [34, 60], coldEdgeF: 32, warmEdgeF: 65 },
    spawning: {
      seasons: ["fall", "late_fall"],
      note: "Generally spawns September through November. Known spawning reaches and concentrations are excluded from target guidance.",
    },
    habitat: {
      waterTypes: ["flowing", "stillwater"],
      riverHolding: ["run", "seam", "pool_head", "pool_tail", "deep_pool", "current_break"],
      stillHolding: ["inlet", "outlet", "rocky_shoreline", "drop_off", "basin"],
      currentPreference: "Resident and migratory fish use cold rivers, streams, connected lakes, and estuarine transitions; current use depends strongly on life-history form.",
      depthTendency: "Resident stream fish use pools and drift lanes; lake/wintering forms may use deeper water, while sea-run fish move through river and coastal transitions.",
      lightResponse: "Clear cold water rewards cover/depth under bright conditions, while drift and low light can allow shallower feeding positions.",
    },
    forageClasses: ["aquatic_insects", "emerging_insects", "eggs", "crustaceans", "small_forage_fish", "larger_prey_fish"],
    flowingPresentations: ["dead_drift", "swing", "bottom_contact_drift", "cross_current_retrieve", "pulse_jig"],
    stillPresentations: ["horizontal_retrieve", "vertical_jig", "slow_drag", "suspend_pause", "trolling"],
    exceptions: [
      "Southern and northern forms differ, and resident versus sea-run life histories should be declared through RPC rather than inferred from a water name.",
      "Egg feeding is plausible in mixed salmon systems but must never be used to target active spawning aggregations or redds.",
    ],
    geographic: "Pacific and Arctic drainages of Alaska and northwestern North America, with resident freshwater and sea-run populations.",
    sources: [
      { label: "Alaska Department of Fish and Game Dolly Varden species profile", class: SRC.agency },
    ],
    reviewedAt: "2026-08-27",
    nextReviewAt: "2026-11-27",
  },
  {
    id: "stenodus_leucichthys",
    scientificName: "Stenodus leucichthys",
    commonNames: ["Sheefish", "Inconnu"],
    group: "trout_salmon",
    targetStatus: "regulated_context",
    nativeContext: "Large northern coregonine predator with resident and exceptionally long-distance migratory populations in Alaska and arctic North America.",
    thermal: { preferredF: [45, 58], activeF: [34, 64], coldEdgeF: 32, warmEdgeF: 68 },
    spawning: {
      seasons: ["fall"],
      note: "Broadcast spawns in late September to early October in very cold flowing water. The few known spawning areas are explicitly excluded from target guidance.",
    },
    habitat: {
      waterTypes: ["flowing", "stillwater"],
      riverHolding: ["run", "deep_pool", "current_break", "pool_head", "pool_tail", "tributary_mouth"],
      stillHolding: ["suspended_open", "inlet", "outlet", "drop_off", "basin"],
      currentPreference: "Migratory adults use large-river travel corridors and forage transitions; resident fish can remain in freshwater lake/river systems year-round.",
      depthTendency: "Adult position is strongly forage- and migration-linked and can range from deep channels to pelagic feeding zones.",
      lightResponse: "Turbidity and northern seasonal light reduce the usefulness of a simple day/night rule; forage position and current often matter more.",
    },
    forageClasses: ["small_forage_fish", "larger_prey_fish", "aquatic_insects"],
    flowingPresentations: ["cross_current_retrieve", "downstream_retrieve", "pulse_jig", "swing"],
    stillPresentations: ["horizontal_retrieve", "vertical_jig", "trolling", "suspend_pause"],
    exceptions: [
      "Adults are strongly piscivorous, while juvenile diet is more invertebrate-oriented; do not average those stages into one forage assumption.",
      "ADF&G documents migrations exceeding 1,000 miles in some populations; named migration chokepoints and spawning areas are not target layers.",
    ],
    geographic: "Large northern Alaska and Canadian river/lake systems, including migratory populations using brackish bays and resident freshwater populations.",
    sources: [
      { label: "Alaska Department of Fish and Game Sheefish species profile", class: SRC.agency },
    ],
    reviewedAt: "2026-08-27",
    nextReviewAt: "2026-11-27",
  },
  {
    id: "acipenser_transmontanus",
    scientificName: "Acipenser transmontanus",
    commonNames: ["White sturgeon"],
    group: "other",
    targetStatus: "regulated_context",
    nativeContext: "Long-lived western North American sturgeon of large river, estuarine, and connected lake systems; population status varies sharply by basin.",
    thermal: { preferredF: [50, 68], activeF: [40, 75], coldEdgeF: 36, warmEdgeF: 80 },
    spawning: {
      seasons: ["spring", "early_summer"],
      note: "Spawning occurs in large-river current over suitable substrate; spawning reaches and endangered population habitat are excluded from target guidance.",
    },
    habitat: {
      waterTypes: ["flowing", "stillwater"],
      riverHolding: ["deep_pool", "run", "current_break", "pool_tail"],
      stillHolding: ["basin", "drop_off", "inlet", "outlet", "riprap"],
      currentPreference: "Large adults are bottom-oriented but use substantial river current and deep channel structure rather than slack-water-only habitat.",
      depthTendency: "Predominantly bottom-associated in deep channels, pools, and connected lake/estuarine habitat; movement can be extensive and seasonal.",
      lightResponse: "Low visibility is not a major barrier because barbels and nonvisual senses support benthic foraging; light is secondary to current, depth, substrate, and prey.",
    },
    forageClasses: ["mollusks", "crustaceans", "worms_annelids", "small_forage_fish", "larger_prey_fish", "eggs"],
    flowingPresentations: ["stationary_bait", "bottom_contact_drift"],
    stillPresentations: ["bottom_contact", "slow_drag", "stationary_bait"],
    exceptions: [
      "White sturgeon can live for many decades and local harvest/catch rules vary sharply; verify jurisdiction before any field action.",
      "The Kootenai River population is federally endangered and must fail closed when that RPC context is explicitly declared.",
    ],
    geographic: "Pacific-slope large rivers and estuarine systems of western North America, plus landlocked populations including the Kootenai system.",
    sources: [
      { label: "U.S. Fish and Wildlife Service White Sturgeon species profile", class: SRC.agency },
      { label: "U.S. Fish and Wildlife Service Kootenai River white sturgeon recovery materials", class: SRC.agency },
    ],
    reviewedAt: "2026-08-27",
    nextReviewAt: "2026-11-27",
  },
  {
    id: "atractosteus_spatula",
    scientificName: "Atractosteus spatula",
    commonNames: ["Alligator gar"],
    group: "predator",
    targetStatus: "regulated_context",
    nativeContext: "Giant long-lived gar native to Mississippi/Gulf drainages and Gulf coastal plain; strongly associated with large rivers, floodplains, backwaters, bayous, and connected lakes.",
    thermal: { preferredF: [68, 82], activeF: [55, 88], coldEdgeF: 48, warmEdgeF: 92 },
    spawning: {
      seasons: ["spring", "early_summer", "summer"],
      note: "Successful spawning is linked to warm seasonal flooding and vegetated inundated habitat. Flooded spawning habitat is an invalidator, not a target map.",
    },
    habitat: {
      waterTypes: ["flowing", "stillwater"],
      riverHolding: ["deep_pool", "eddy", "side_channel", "current_break", "submerged_wood"],
      stillHolding: ["basin", "inlet", "wood", "weed_edge", "shallow_flat", "drop_off"],
      currentPreference: "Uses large-river pools, backwaters, side channels, and floodplain-connected habitat; generally favors lower-velocity feeding zones over the fastest current core.",
      depthTendency: "Large fish can use deep main-channel pools and open water but shift into shallow connected habitat under favorable seasonal conditions.",
      lightResponse: "Sight and vibration-based predation can occur day or night; surface air-gulping is respiratory behavior and must not be interpreted as surface feeding.",
    },
    forageClasses: ["larger_prey_fish", "small_forage_fish", "crustaceans", "amphibians"],
    flowingPresentations: ["stationary_bait", "cross_current_retrieve", "pulse_jig"],
    stillPresentations: ["live_natural_bait_suspension", "horizontal_retrieve", "stop_and_go", "subsurface_slow_roll", "stationary_bait"],
    exceptions: [
      "Air-gulping at the surface is not feeding evidence.",
      "Long lifespan, late maturity, episodic recruitment, and special harvest rules make local regulation/conservation context essential.",
    ],
    geographic: "Mississippi drainage and Gulf coastal plain from the central United States south into Mexico, with strongest fit in large low-gradient river/floodplain systems.",
    sources: [
      { label: "U.S. Fish and Wildlife Service Alligator Gar species profile", class: SRC.agency },
      { label: "State and USFWS alligator gar life-history and floodplain recruitment literature", class: SRC.agency },
    ],
    reviewedAt: "2026-08-27",
    nextReviewAt: "2026-11-27",
  },
  {
    id: "catostomus_commersonii",
    scientificName: "Catostomus commersonii",
    commonNames: ["White sucker"],
    group: "other",
    nativeContext: "Widespread North American catostomid occupying an unusually broad range of cool/warm, clear/turbid, flowing/standing fresh waters.",
    thermal: { preferredF: [55, 68], activeF: [42, 75], coldEdgeF: 36, warmEdgeF: 82 },
    spawning: {
      seasons: ["early_spring", "spring", "early_summer"],
      note: "Spawns from April into June, often after upstream movement to gravel/rocky shoals. Spawning runs are excluded from target guidance.",
    },
    habitat: {
      waterTypes: ["flowing", "stillwater"],
      riverHolding: ["pool_tail", "run", "current_break", "deep_pool", "side_channel"],
      stillHolding: ["basin", "drop_off", "inlet", "shallow_flat", "riprap"],
      currentPreference: "Highly adaptable but generally avoids the fastest current; bottom feeding is strongest in moderate/slow lanes and impoundments.",
      depthTendency: "Predominantly benthic from shallow flats to deeper basin/river pools depending on season and temperature.",
      lightResponse: "Bottom-oriented sensory feeding makes light secondary to substrate, invertebrate availability, and current delivery.",
    },
    forageClasses: ["aquatic_insects", "worms_annelids", "crustaceans"],
    flowingPresentations: ["bottom_contact_drift", "stationary_bait", "pulse_jig"],
    stillPresentations: ["bottom_contact", "slow_drag", "live_natural_bait_suspension"],
    exceptions: [
      "White sucker and longnose sucker readily hybridize in some systems; identification should not be inferred from habitat alone.",
      "Adults also consume algae/detritus that the presentation-family vocabulary does not model as a forage class.",
    ],
    geographic: "Broadly distributed through northern and eastern North America and widely established elsewhere; lakes, reservoirs, streams, and rivers.",
    sources: [
      { label: "Montana Field Guide White Sucker species account", class: SRC.agency },
    ],
    reviewedAt: "2026-08-27",
    nextReviewAt: "2026-11-27",
  },
  {
    id: "catostomus_catostomus",
    scientificName: "Catostomus catostomus",
    commonNames: ["Longnose sucker"],
    group: "other",
    nativeContext: "Northern coldwater sucker of clear streams and lakes, with broad circumpolar North American distribution and stronger cold/clean-substrate association than white sucker.",
    thermal: { preferredF: [48, 62], activeF: [38, 70], coldEdgeF: 34, warmEdgeF: 76 },
    spawning: {
      seasons: ["spring", "early_summer"],
      note: "Spawns April into early July over loose gravel riffles; Montana reports spawning around 54–59°F. Spawning riffles are excluded from target guidance.",
    },
    habitat: {
      waterTypes: ["flowing", "stillwater"],
      riverHolding: ["riffle_to_run", "run", "pool_tail", "current_break", "deep_pool"],
      stillHolding: ["rocky_shoreline", "drop_off", "inlet", "basin"],
      currentPreference: "Uses cold clear streams and moderate current more readily than white sucker while remaining strongly bottom-oriented.",
      depthTendency: "Benthic in both lakes and streams, shifting among riffle/run feeding areas, pool refuge, and lake depth/substrate edges.",
      lightResponse: "Light is secondary to substrate, current, and benthic food; clear bright water can reinforce slightly deeper use.",
    },
    forageClasses: ["aquatic_insects", "worms_annelids", "crustaceans"],
    flowingPresentations: ["bottom_contact_drift", "stationary_bait", "pulse_jig"],
    stillPresentations: ["bottom_contact", "slow_drag", "live_natural_bait_suspension"],
    exceptions: [
      "Longnose sucker diet also includes algae; this model represents the animal-food component that maps to presentation mechanics.",
      "Do not collapse longnose and white sucker simply because both occur in the same water and can hybridize.",
    ],
    geographic: "Northern North America in cold lakes and rivers, extending through interior and western systems including Montana and Alaska.",
    sources: [
      { label: "Montana Field Guide Longnose Sucker species account", class: SRC.agency },
    ],
    reviewedAt: "2026-08-27",
    nextReviewAt: "2026-11-27",
  },
  {
    id: "catostomus_macrocheilus",
    scientificName: "Catostomus macrocheilus",
    commonNames: ["Largescale sucker"],
    group: "other",
    nativeContext: "Western North American sucker native to Pacific-slope/interior drainages; occupies both lakes and rivers and feeds broadly on substrate organisms.",
    thermal: { preferredF: [55, 70], activeF: [42, 78], coldEdgeF: 36, warmEdgeF: 84 },
    spawning: {
      seasons: ["spring"],
      note: "Spawns primarily April–May in strong-current gravel riffles or along lake margins. Spawning migrations and riffles are invalidators, not target layers.",
    },
    habitat: {
      waterTypes: ["flowing", "stillwater"],
      riverHolding: ["run", "pool_tail", "current_break", "deep_pool", "riffle_to_run"],
      stillHolding: ["rocky_shoreline", "drop_off", "basin", "inlet", "shallow_flat"],
      currentPreference: "Adults occupy a broad range of river velocities and lake habitats but feed primarily at the substrate; juveniles favor quiet backwaters/lakes.",
      depthTendency: "Predominantly benthic, moving between shallow substrate feeding zones and deeper pools/basins with season and disturbance.",
      lightResponse: "Bottom feeding makes light a secondary modifier relative to substrate and available benthic organisms.",
    },
    forageClasses: ["aquatic_insects", "crustaceans", "worms_annelids", "mollusks"],
    flowingPresentations: ["bottom_contact_drift", "stationary_bait", "pulse_jig"],
    stillPresentations: ["bottom_contact", "slow_drag", "live_natural_bait_suspension"],
    exceptions: [
      "Cold dam releases can delay spawning timing; calendar alone should not imply reproductive state.",
      "The species feeds on almost any available substrate organism, so observed forage should outrank a generic assumed diet.",
    ],
    geographic: "Western North America, especially Pacific-drainage and interior western rivers/lakes; native in Montana's western drainage.",
    sources: [
      { label: "Montana Field Guide Largescale Sucker species account", class: SRC.agency },
    ],
    reviewedAt: "2026-08-27",
    nextReviewAt: "2026-11-27",
  },
  {
    id: "ameiurus_catus",
    scientificName: "Ameiurus catus",
    commonNames: ["White catfish"],
    group: "other",
    nativeContext: "Atlantic/Gulf-slope catfish of freshwater and brackish coastal systems; this record covers freshwater rivers, reservoirs, lakes, and slow tributaries only.",
    thermal: { preferredF: [68, 80], activeF: [55, 86], coldEdgeF: 48, warmEdgeF: 90 },
    spawning: {
      seasons: ["early_summer", "summer"],
      note: "Late-spring/summer cavity or depression spawning around banks, roots, and structure; guarded nests are not target cues.",
    },
    habitat: {
      waterTypes: ["flowing", "stillwater"],
      riverHolding: ["deep_pool", "current_break", "submerged_wood", "side_channel", "eddy"],
      stillHolding: ["basin", "wood", "riprap", "inlet", "drop_off"],
      currentPreference: "Uses slow to moderate coastal-river and reservoir habitat; favors bottom structure and current relief over fast water.",
      depthTendency: "Bottom-oriented from shallow cover to deeper holes and basins, with movement shallower to forage under favorable conditions.",
      lightResponse: "More willing to feed during daylight than many bullheads, while still using scent/taste and bottom contact heavily.",
    },
    forageClasses: ["small_forage_fish", "aquatic_insects", "crustaceans", "mollusks", "worms_annelids"],
    flowingPresentations: ["stationary_bait", "bottom_contact_drift", "pulse_jig"],
    stillPresentations: ["bottom_contact", "slow_drag", "live_natural_bait_suspension"],
    exceptions: [
      "Fresh/brackish tolerance is not a license to use this freshwater model in tidal saltwater without a reviewed salinity layer.",
      "White catfish should not silently inherit brown/black/yellow bullhead nocturnal weighting.",
    ],
    geographic: "Atlantic and Gulf coastal drainages of the eastern/southeastern United States, with introductions beyond the native range.",
    sources: [
      { label: "State wildlife agency White Catfish species accounts", class: SRC.agency },
    ],
    reviewedAt: "2026-08-27",
    nextReviewAt: "2026-11-27",
  },
  {
    id: "lepomis_megalotis",
    scientificName: "Lepomis megalotis",
    commonNames: ["Longear sunfish"],
    group: "bass_panfish",
    nativeContext: "Colorful central/eastern North American sunfish strongly associated with clear permanent-flowing streams, pools, rocky/sandy substrate, and aquatic vegetation.",
    thermal: { preferredF: [68, 80], activeF: [58, 84], coldEdgeF: 50, warmEdgeF: 90 },
    spawning: {
      seasons: ["early_summer", "summer", "late_summer"],
      note: "Colonial nesting can extend from mid-May into August. Nest colonies are conservation/ethics context, not a targeting recommendation.",
    },
    habitat: {
      waterTypes: ["flowing", "stillwater"],
      riverHolding: ["eddy", "side_channel", "current_break", "pool_tail", "submerged_wood"],
      stillHolding: ["weed_edge", "shallow_flat", "rocky_shoreline", "wood", "inlet"],
      currentPreference: "Stream-oriented but avoids strong current; favors pools, inlets, overflow water, and protected edges adjacent to moving water.",
      depthTendency: "Primarily shallow-to-mid littoral/pool fish around rock, sand, vegetation, and current relief.",
      lightResponse: "Strongly daytime-active sight feeder; clear water and structure support visual insect/crustacean feeding.",
    },
    forageClasses: ["aquatic_insects", "terrestrial_insects", "crustaceans", "small_forage_fish"],
    flowingPresentations: ["dead_drift", "stationary_bait", "pulse_jig"],
    stillPresentations: ["drop_presentation", "slow_drag", "surface_retrieve", "live_natural_bait_suspension"],
    exceptions: [
      "Longear sunfish are more stream-associated than bluegill but still avoid the fastest current core.",
      "Spawning males can be unusually visible and territorial; nest visibility is not a recommendation to target colonies.",
    ],
    geographic: "Central and eastern North America, especially clear rocky/sandy streams and connected impoundments of the interior.",
    sources: [
      { label: "Missouri Department of Conservation Longear Sunfish field guide", class: SRC.agency },
    ],
    reviewedAt: "2026-08-27",
    nextReviewAt: "2026-11-27",
  },
  {
    id: "centrarchus_macropterus",
    scientificName: "Centrarchus macropterus",
    commonNames: ["Flier"],
    group: "bass_panfish",
    nativeContext: "Southeastern/coastal-plain sunfish of swampy backwaters, sloughs, oxbows, slow creeks, and heavily vegetated low-gradient water.",
    thermal: { preferredF: [62, 76], activeF: [52, 82], coldEdgeF: 46, warmEdgeF: 86 },
    spawning: {
      seasons: ["spring"],
      note: "Early spring nesting begins around low-to-upper 60s °F in southern waters. Nests and spawning groups are excluded from targeting logic.",
    },
    habitat: {
      waterTypes: ["stillwater", "flowing"],
      riverHolding: ["eddy", "side_channel", "submerged_wood", "deep_pool"],
      stillHolding: ["weed_edge", "inside_weedline", "wood", "shallow_flat", "inlet", "dock_shade"],
      currentPreference: "Strongest fit is slack to very slow, vegetated, tannic or clear backwater rather than sustained current.",
      depthTendency: "Usually shallow-to-mid around vegetation, wood, and protected backwater structure.",
      lightResponse: "Cover and tannic water reduce high-sun exposure; insect/invertebrate feeding remains plausible throughout daylight in protected habitat.",
    },
    forageClasses: ["aquatic_insects", "worms_annelids", "mollusks", "crustaceans", "small_forage_fish", "zooplankton"],
    flowingPresentations: ["stationary_bait", "pulse_jig", "dead_drift"],
    stillPresentations: ["drop_presentation", "slow_drag", "live_natural_bait_suspension", "surface_retrieve"],
    exceptions: [
      "Flier habitat is low-gradient backwater; do not apply generic river-current sunfish mechanics simply because the water is technically flowing.",
      "Young and adult diet breadth is high; observed forage should outrank an assumed single prey class.",
    ],
    geographic: "Southeastern U.S. coastal plain and lower-gradient Atlantic/Gulf drainage backwaters, swamps, oxbows, and slow tributaries.",
    sources: [
      { label: "South Carolina Department of Natural Resources Flier species account", class: SRC.agency },
      { label: "Southeastern state flier life-history syntheses", class: SRC.syn },
    ],
    reviewedAt: "2026-08-27",
    nextReviewAt: "2026-11-27",
  },
];
