export const SPECIES_IMAGE_MODEL_VERSION = "IMG-1.0" as const;

export type SpeciesImageRecord = {
  speciesId: string;
  canonical: string;
  thumb: string;
  sourcePage: string;
  sourceOrg: string;
  creator: string;
  license: string;
  imageType: "photograph" | "field_photograph" | "specimen_photograph" | "scientific_illustration";
  /**
   * How the species identification was established.
   * "authoritative_source" — the publishing body (USFWS, USGS, a state agency)
   *   labelled the subject, and the label carries the identification.
   * "visual_review" — the asset came from a library whose keywords are not a
   *   reliable identification (stock search returns the wrong species routinely),
   *   so the identification rests on the diagnostic features named in visualQa.
   */
  identificationBasis?: "authoritative_source" | "visual_review";
  identificationConfidence: "high";
  visualQa: string;
  reviewedAt: string;
};

export const SPECIES_IMAGES: SpeciesImageRecord[] = [
  {
    speciesId: "oncorhynchus_nerka_anadromous",
    canonical: "/species/sockeye-salmon/canonical.webp",
    thumb: "/species/sockeye-salmon/thumb.webp",
    sourcePage: "https://www.fws.gov/media/sockeye-salmon-68",
    sourceOrg: "U.S. Fish and Wildlife Service",
    creator: "Ryan Hagerty / USFWS",
    license: "Public Domain — U.S. federal government work",
    imageType: "photograph",
    identificationConfidence: "high",
    visualQa: "USFWS species-labeled underwater photograph of migrating sockeye salmon. Adult body and salmon morphology are visible in natural river habitat; the image is identity/context evidence, not a location or run-strength recommendation.",
    reviewedAt: "2026-08-27",
  },
  {
    speciesId: "oncorhynchus_gorbuscha",
    canonical: "/species/pink-salmon/canonical.webp",
    thumb: "/species/pink-salmon/thumb.webp",
    sourcePage: "https://www.fws.gov/media/pink-salmon-dosewallips-river-washington",
    sourceOrg: "U.S. Fish and Wildlife Service",
    creator: "Roger Tabor / USFWS",
    license: "Public Domain — U.S. federal government work",
    imageType: "photograph",
    identificationConfidence: "high",
    visualQa: "USFWS species-labeled 5184×3888 underwater photograph of pink salmon in the Dosewallips River. The leading fish shows adult head and body morphology in natural habitat; background fish are secondary context.",
    reviewedAt: "2026-08-27",
  },
  {
    speciesId: "oncorhynchus_keta",
    canonical: "/species/chum-salmon/canonical.webp",
    thumb: "/species/chum-salmon/thumb.webp",
    sourcePage: "https://www.fws.gov/media/chum-salmon",
    sourceOrg: "U.S. Fish and Wildlife Service",
    creator: "Ryan Hagerty / USFWS",
    license: "Public Domain",
    imageType: "photograph",
    identificationConfidence: "high",
    visualQa: "USFWS species-labeled underwater chum salmon photograph. The characteristic adult freshwater body pattern and lateral form are visible in natural habitat.",
    reviewedAt: "2026-08-27",
  },
  {
    speciesId: "salmo_salar_landlocked",
    canonical: "/species/landlocked-atlantic-salmon/canonical.webp",
    thumb: "/species/landlocked-atlantic-salmon/thumb.webp",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Salmo_salar_(crop).jpg",
    sourceOrg: "U.S. Fish and Wildlife Service",
    creator: "Ryan Hagerty / USFWS",
    license: "Public Domain — U.S. federal government work",
    imageType: "scientific_illustration",
    identificationConfidence: "high",
    visualQa: "Species-level Salmo salar morphology only; landlocked life history is supplied by the reviewed record, not inferred from the image.",
    reviewedAt: "2026-08-27",
  },
  {
    speciesId: "salvelinus_alpinus",
    canonical: "/species/arctic-char/canonical.webp",
    thumb: "/species/arctic-char/thumb.webp",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Salvelinus_alpinus_256781750_(cropped).jpg",
    sourceOrg: "iNaturalist / Wikimedia Commons",
    creator: "Igor Zagrebin",
    license: "CC0 1.0 Public Domain Dedication",
    imageType: "photograph",
    identificationConfidence: "high",
    visualQa: "Lateral char photograph with body pattern and fin profile visible; retained separately from Dolly Varden identity imagery.",
    reviewedAt: "2026-08-27",
  },
  {
    speciesId: "salvelinus_malma",
    canonical: "/species/dolly-varden/canonical.webp",
    thumb: "/species/dolly-varden/thumb.webp",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Salvelinus_malma_malma_from_Quicksilver_Creek.jpg",
    sourceOrg: "U.S. Fish and Wildlife Service",
    creator: "Jim Gaither / USFWS",
    license: "Public Domain — U.S. federal government work",
    imageType: "photograph",
    identificationConfidence: "high",
    visualQa: "USFWS-labeled Dolly Varden with lateral pattern visible. Identification is not inferred from geography.",
    reviewedAt: "2026-08-27",
  },
  {
    speciesId: "stenodus_leucichthys",
    canonical: "/species/sheefish/canonical.webp",
    thumb: "/species/sheefish/thumb.webp",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Stenodus_leucichthys.jpg",
    sourceOrg: "Brockhaus and Efron Encyclopedic Dictionary / Wikimedia Commons",
    creator: "Historical scientific illustration",
    license: "Public Domain — pre-1907 historical work",
    imageType: "scientific_illustration",
    identificationConfidence: "high",
    visualQa: "Full-lateral sheefish illustration chosen instead of a spawning-population field photograph so identity art does not encourage aggregation targeting.",
    reviewedAt: "2026-08-27",
  },
  {
    speciesId: "acipenser_transmontanus",
    canonical: "/species/white-sturgeon/canonical.webp",
    thumb: "/species/white-sturgeon/thumb.webp",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Acipenser_transmontanus_(FDA_286).jpg",
    sourceOrg: "U.S. Food and Drug Administration Reference Standard Sequence Library",
    creator: "U.S. Food and Drug Administration / J. Deeds",
    license: "Public Domain — U.S. federal government work",
    imageType: "specimen_photograph",
    identificationConfidence: "high",
    visualQa: "Federal reference-identification photograph. Population and conservation status are never inferred from morphology alone.",
    reviewedAt: "2026-08-27",
  },
  {
    speciesId: "atractosteus_spatula",
    canonical: "/species/alligator-gar/canonical.webp",
    thumb: "/species/alligator-gar/thumb.webp",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Alligator_gar_held_boatside_1_October_2021.png",
    sourceOrg: "U.S. Fish and Wildlife Service",
    creator: "Ryan Hagerty / USFWS",
    license: "Public Domain — U.S. federal government work",
    imageType: "field_photograph",
    identificationConfidence: "high",
    visualQa: "Authoritative full alligator gar field photograph. Human/boat context makes it a canonical fallback; replace only with a cleaner equally authoritative whole-fish image.",
    reviewedAt: "2026-08-27",
  },
  {
    speciesId: "catostomus_commersonii",
    canonical: "/species/white-sucker/canonical.webp",
    thumb: "/species/white-sucker/thumb.webp",
    sourcePage: "https://commons.wikimedia.org/wiki/File:White_sucker_(51247865900).jpg",
    sourceOrg: "U.S. Fish and Wildlife Service Mountain-Prairie",
    creator: "Sam Stukel / USFWS",
    license: "Public Domain — U.S. federal government work",
    imageType: "photograph",
    identificationConfidence: "high",
    visualQa: "High-resolution USFWS white sucker photograph with explicit species identity and clearly visible morphology.",
    reviewedAt: "2026-08-27",
  },
  {
    speciesId: "catostomus_catostomus",
    canonical: "/species/longnose-sucker/canonical.webp",
    thumb: "/species/longnose-sucker/thumb.webp",
    sourcePage: "https://commons.wikimedia.org/wiki/File:LongnoseSucker.jpg",
    sourceOrg: "U.S. Fish and Wildlife Service",
    creator: "U.S. Fish and Wildlife Service",
    license: "Public Domain — U.S. federal government work",
    imageType: "photograph",
    identificationConfidence: "high",
    visualQa: "High-resolution USFWS longnose sucker photograph; kept visually and biologically distinct from white sucker despite possible co-occurrence/hybridization.",
    reviewedAt: "2026-08-27",
  },
  {
    speciesId: "catostomus_macrocheilus",
    canonical: "/species/largescale-sucker/canonical.webp",
    thumb: "/species/largescale-sucker/thumb.webp",
    sourcePage: "https://commons.wikimedia.org/wiki/File:FMIB_34320_Catostomus_macrochilus_Grd.jpeg",
    sourceOrg: "U.S. Fish Commission / Freshwater and Marine Image Bank",
    creator: "Historical U.S. Fish Commission illustration",
    license: "Public Domain — historical government collection",
    imageType: "scientific_illustration",
    identificationConfidence: "high",
    visualQa: "Full-lateral, explicitly labeled largescale sucker illustration. Suitable for canonical identity, not editorial habitat use.",
    reviewedAt: "2026-08-27",
  },
  {
    speciesId: "ameiurus_catus",
    canonical: "/species/white-catfish/canonical.webp",
    thumb: "/species/white-catfish/thumb.webp",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Ameiurus_catus_FWS_20900.jpg",
    sourceOrg: "U.S. Fish and Wildlife Service",
    creator: "Matthew Patterson / USFWS",
    license: "Public Domain — U.S. federal government work",
    imageType: "photograph",
    identificationConfidence: "high",
    visualQa: "4,288-pixel USFWS identification photograph with barbels, fins, flank and caudal profile clearly visible.",
    reviewedAt: "2026-08-27",
  },
  {
    speciesId: "lepomis_megalotis",
    canonical: "/species/longear-sunfish/canonical.webp",
    thumb: "/species/longear-sunfish/thumb.webp",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Longear_sunfish_lepomis_megalotis.jpg",
    sourceOrg: "U.S. Fish and Wildlife Service National Digital Library",
    creator: "Duane Raver / USFWS",
    license: "Public Domain",
    imageType: "scientific_illustration",
    identificationConfidence: "high",
    visualQa: "Large full-lateral USFWS illustration clearly showing the opercular flap and deep-bodied Lepomis morphology.",
    reviewedAt: "2026-08-27",
  },
  {
    speciesId: "centrarchus_macropterus",
    canonical: "/species/flier/canonical.webp",
    thumb: "/species/flier/thumb.webp",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Centrarchus_macropterus.jpg",
    sourceOrg: "U.S. Fish and Wildlife Service",
    creator: "Duane Raver / USFWS",
    license: "Public Domain — U.S. federal government work",
    imageType: "scientific_illustration",
    identificationConfidence: "high",
    visualQa: "USFWS-labeled full-lateral flier illustration with unobstructed deep body and fin morphology.",
    reviewedAt: "2026-08-27",
  },
  {
    speciesId: "salmo_trutta",
    canonical: "/species/brown-trout/canonical.webp",
    thumb: "/species/brown-trout/thumb.webp",
    sourcePage: "https://stock.adobe.com/images/id/578037819",
    sourceOrg: "Adobe Stock",
    creator: "Adobe Stock contributor · asset 578037819",
    license: "Adobe Stock Standard licence",
    imageType: "photograph",
    identificationBasis: "visual_review",
    identificationConfidence: "high",
    visualQa: "Full lateral adult filling the frame against a green riverbed. Identified on diagnostic features rather than the stock keywords: dense black flank spotting, red/orange spots ringed with pale halos along the lateral line, and an essentially unspotted tail — which separates it from rainbow trout. Adipose fin and blunt snout visible. Photographic, with no generative artefacts in fins, eye or background falloff.",
    reviewedAt: "2026-08-29",
  },
  {
    speciesId: "oncorhynchus_mykiss",
    canonical: "/species/rainbow-trout/canonical.webp",
    thumb: "/species/rainbow-trout/thumb.webp",
    sourcePage: "https://stock.adobe.com/images/id/162652496",
    sourceOrg: "Adobe Stock",
    creator: "Adobe Stock contributor · asset 162652496",
    license: "Adobe Stock Standard licence",
    imageType: "photograph",
    identificationBasis: "visual_review",
    identificationConfidence: "high",
    visualQa: "Full lateral adult in open water against a plain teal ground. Identified on fine black spotting carried across the body AND the tail, plus the silvery-pink lateral band, with no halo-ringed red spots — the combination that separates it from brown trout. Photographic; fins and eye are anatomically coherent.",
    reviewedAt: "2026-08-29",
  },
  {
    speciesId: "micropterus_nigricans",
    canonical: "/species/largemouth-bass/canonical.webp",
    thumb: "/species/largemouth-bass/thumb.webp",
    sourcePage: "https://stock.adobe.com/images/id/369696445",
    sourceOrg: "Adobe Stock",
    creator: "Adobe Stock contributor · asset 369696445",
    license: "Adobe Stock Standard licence",
    imageType: "field_photograph",
    identificationBasis: "visual_review",
    identificationConfidence: "high",
    visualQa: "Adult holding beside submerged wood in stained water. Identified on the upper jaw extending past the rear margin of the eye — the feature that separates largemouth from smallmouth — with the blotchy lateral band and deeply notched dorsal consistent. The wood is habitat context, not a location claim. Photographic: natural light shafts, coherent debris, plausible surface refraction.",
    reviewedAt: "2026-08-29",
  },
  {
    speciesId: "esox_lucius",
    canonical: "/species/northern-pike/canonical.webp",
    thumb: "/species/northern-pike/thumb.webp",
    sourcePage: "https://stock.adobe.com/images/id/165356927",
    sourceOrg: "Adobe Stock",
    creator: "Adobe Stock contributor · asset 165356927",
    license: "Adobe Stock Standard licence",
    imageType: "field_photograph",
    identificationBasis: "visual_review",
    identificationConfidence: "high",
    visualQa: "Full lateral adult among submerged weed. Identified on the duck-bill snout, pale bean-shaped spots on a dark green ground, and the single soft dorsal set far back — separating it from muskellunge, which carries dark markings on a pale ground. Weed is habitat context, not a location claim. Photographic.",
    reviewedAt: "2026-08-29",
  },
];

export const SPECIES_IMAGES_BY_ID = Object.fromEntries(
  SPECIES_IMAGES.map((record) => [record.speciesId, record]),
) as Record<string, SpeciesImageRecord>;
