/* GENERATED by scripts/build-species-images.mjs — do not edit by hand. */

/**
 * The candidate ladder for each reviewed photograph, and the real pixel size of
 * the largest rung.
 *
 * The intrinsic size is here so every `<img>` can declare width and height and
 * reserve its own space. Without it, a species page reflowed the moment the
 * photograph arrived — which on a phone on a bad connection is the moment
 * somebody is already reading.
 */
export type SpeciesImageLadder = {
  /** Real pixel dimensions of `canonical.webp`. */
  intrinsic: { width: number; height: number };
  /** Every width available as a `srcset` candidate, ascending. */
  widths: number[];
};

export const SPECIES_IMAGE_LADDERS: Record<string, SpeciesImageLadder> = {
  "alligator-gar": {
    intrinsic: {
      width: 1410,
      height: 944,
    },
    widths: [400, 800, 1410],
  },
  "arctic-char": {
    intrinsic: {
      width: 1600,
      height: 686,
    },
    widths: [400, 800, 1600],
  },
  "brown-trout": {
    intrinsic: {
      width: 900,
      height: 600,
    },
    widths: [400, 800, 900],
  },
  "chum-salmon": {
    intrinsic: {
      width: 1600,
      height: 1067,
    },
    widths: [400, 800, 1600],
  },
  "dolly-varden": {
    intrinsic: {
      width: 1050,
      height: 697,
    },
    widths: [400, 800, 1050],
  },
  flier: {
    intrinsic: {
      width: 1138,
      height: 750,
    },
    widths: [400, 800, 1138],
  },
  "landlocked-atlantic-salmon": {
    intrinsic: {
      width: 1600,
      height: 512,
    },
    widths: [400, 800, 1600],
  },
  "largemouth-bass": {
    intrinsic: {
      width: 900,
      height: 600,
    },
    widths: [400, 800, 900],
  },
  "largescale-sucker": {
    intrinsic: {
      width: 973,
      height: 405,
    },
    widths: [400, 800, 973],
  },
  "longear-sunfish": {
    intrinsic: {
      width: 1600,
      height: 972,
    },
    widths: [400, 800, 1600],
  },
  "longnose-sucker": {
    intrinsic: {
      width: 1600,
      height: 1063,
    },
    widths: [400, 800, 1600],
  },
  "northern-pike": {
    intrinsic: {
      width: 900,
      height: 600,
    },
    widths: [400, 800, 900],
  },
  "pink-salmon": {
    intrinsic: {
      width: 1600,
      height: 1200,
    },
    widths: [400, 800, 1600],
  },
  "rainbow-trout": {
    intrinsic: {
      width: 900,
      height: 600,
    },
    widths: [400, 800, 900],
  },
  sheefish: {
    intrinsic: {
      width: 1137,
      height: 467,
    },
    widths: [400, 800, 1137],
  },
  "sockeye-salmon": {
    intrinsic: {
      width: 1600,
      height: 1067,
    },
    widths: [400, 800, 1600],
  },
  "white-catfish": {
    intrinsic: {
      width: 1600,
      height: 1063,
    },
    widths: [400, 800, 1600],
  },
  "white-sturgeon": {
    intrinsic: {
      width: 1280,
      height: 960,
    },
    widths: [400, 800, 1280],
  },
  "white-sucker": {
    intrinsic: {
      width: 1600,
      height: 900,
    },
    widths: [400, 800, 1600],
  },
};
