/**
 * SPO-1.3 — species-specific weighting for the saltwater catalog.
 *
 * These rules are the layer that makes a marine reading answer a *condition*
 * rather than repeat a ranking. The generic model already knows that a falling
 * tide favours drift presentations; what it does not know is that red drum
 * disperse across a flooded marsh and concentrate as it drains, or that
 * bonefish are simply not on a shallow flat at low slack because there is not
 * enough water over it.
 *
 * Every rule here was derived from that species' own reviewed record — the
 * catalog entry and the four dossiers — and not from general angling lore. A
 * species whose record supported nothing is recorded as `policy_only` with an
 * empty rule set rather than given plausible-looking deltas: twelve of the
 * thirty-six are in that state, which is the honest number.
 *
 * Species with `targetStatus: "conservation_sensitive"` or `"non_target"`
 * carry no rules at all, because they carry no presentation guidance anywhere.
 */

import type { ScenarioInput, ThermalState } from "../protocol/types.ts";
import {
  matchesOverrideRule,
  type SpeciesWeightOverrideRule,
} from "./species-weight-overrides.ts";
import type { SpeciesOverrideCoverageRecord } from "./species-weight-overrides-expansion.ts";

export const SPECIES_OVERRIDE_MARINE_VERSION = "SPO-1.3" as const;

const REVIEWED_AT = "2026-08-30";

export const SPECIES_OVERRIDE_MARINE_COVERAGE: SpeciesOverrideCoverageRecord[] = [
  { speciesId: "albula_vulpes", mode: "weighted", note: "Bonefish weighting is built around water-level access rather than a fed/not-fed tide preference: telemetry shows tide height determines whether shallow foraging ground is even reachable, and a strong day/night split layers on top of that.", reviewedAt: REVIEWED_AT },
  { speciesId: "archosargus_probatocephalus", mode: "no_reviewed_rule", note: "Sheepshead genuinely support no weighting rule. The record explicitly rejects a tide-stage relationship (food is attached to structure, not delivered past it), reports no diel pattern, and the one dietary shift it documents (toward plants and detritus) has no class in the forage vocabulary to condition on.", reviewedAt: REVIEWED_AT },
  { speciesId: "atractoscion_nobilis", mode: "weighted", note: "White seabass's weighting reflects a peer-reviewed telemetry-documented seasonal depth shift over the same nearshore reef/kelp structure, without treating the spawning window as a location or timing cue.", reviewedAt: REVIEWED_AT },
  { speciesId: "bodianus_pulcher", mode: "no_reviewed_rule", note: "California sheephead's reviewed record does not support a presentation-family rule: current/tide is explicitly undocumented, all three reviewed nearshore families are already structure-tight so a diurnal light claim has nothing to differentiate against, the seasonal calendar states plainly that no seasonal presentation shift is documented, and the species' key dietary item (sea urchins) has no matching forage class in the reviewed vocabulary.", reviewedAt: REVIEWED_AT },
  { speciesId: "carcharhinus_brevipinna", mode: "weighted", note: "Sourcing gaps are real here (no thermal band, no current-facing or light data, diet and behavior both marked partial), so only the one clearly reviewed mechanical trait -- pursuit of baitfish schools -- is turned into a rule.", reviewedAt: REVIEWED_AT },
  { speciesId: "carcharhinus_limbatus", mode: "weighted", note: "Blacktip's dossier is reviewed rather than partial and supports two grounded mechanics: a documented winter cold-water aggregation and a pursuit-of-baitfish feeding pattern; both stay inside the water types and families the species is actually reviewed for and stop short of naming the aggregation as a place.", reviewedAt: REVIEWED_AT },
  { speciesId: "centropomus_undecimalis", mode: "weighted", note: "Snook weighting is limited to the one clean behavioral statement in the record, a current-facing ambush posture, and deliberately does not pick a tide direction the sources never resolved.", reviewedAt: REVIEWED_AT },
  { speciesId: "centropristis_striata", mode: "weighted", note: "Black sea bass weighting expresses two documented mechanics: sheltering/inactivity when bottom water is cold, and a bright-light structure-hugging / low-light bottom-ranging split, in both reviewed water types.", reviewedAt: REVIEWED_AT },
  { speciesId: "coryphaena_hippurus", mode: "weighted", note: "Mahi-mahi's weighting layers a search phase (finding the weed line or rip), a daytime-visual boost, and a worked-school phase once a school is actually holding under structure, all from the same well-sourced reviewed record.", reviewedAt: REVIEWED_AT },
  { speciesId: "cynoscion_nebulosus", mode: "weighted", note: "Spotted seatrout weighting rests on the record's strongest signal, a documented day/night habitat and movement switch, rather than on tide: no source located ties this species to a preferred tide stage, and none is invented here.", reviewedAt: REVIEWED_AT },
  { speciesId: "cynoscion_regalis", mode: "weighted", note: "Weakfish weighting rests on the record's one strong diel-feeding statement rather than tide, which the record explicitly says was not sourced as a tide-stage relationship.", reviewedAt: REVIEWED_AT },
  { speciesId: "hippoglossus_stenolepis", mode: "weighted", note: "Pacific halibut weighting expresses the one documented departure from strict bottom-ambush behavior: fish will leave the bottom opportunistically to intercept pelagic baitfish when that forage is verified.", reviewedAt: REVIEWED_AT },
  { speciesId: "kajikia_audax", mode: "weighted", note: "Striped marlin's weighting is built on its two clearest reviewed traits -- frontal-zone current-facing and a diurnal, visually-driven hunting style -- and deliberately stops at the two approved offshore feature classes without keying on the seamount holding class the record also lists.", reviewedAt: REVIEWED_AT },
  { speciesId: "lutjanus_analis", mode: "weighted", note: "Mutton snapper weighting expresses the one mechanic the record ties to a scenario condition: current sweeping prey past holding structure rather than the fish working open tide lines. Its documented lunar-aggregation spawning behavior is deliberately excluded from any rule.", reviewedAt: REVIEWED_AT },
  { speciesId: "lutjanus_campechanus", mode: "no_reviewed_rule", note: "No condition in the reviewed record moves red snapper off the generic model. Current/tide, light, and diel behavior are all explicitly undocumented; the thermal figures on file are lab survival/tolerance bounds, not a behavior claim; feeding modes are recorded as ambush/opportunistic/benthic (no pursuit mode); and the species' aggregation and spawning-habitat detail is deliberately withheld from this record, so no rule can be tied to it.", reviewedAt: REVIEWED_AT },
  { speciesId: "megalops_atlanticus", mode: "policy_only", note: "Tarpon are targetStatus conservation_sensitive (catch-and-release only in Florida's largest jurisdiction, no stock assessment, unknown population status), so this record carries no presentation guidance of any kind.", reviewedAt: REVIEWED_AT },
  { speciesId: "mycteroperca_microlepis", mode: "weighted", note: "Gag weighting is restricted to the one non-seasonal mechanic the record supports: a documented pursuit mode that activates when fish forage is actually observed. No thermal, tide, light, or seasonal presentation shift is documented for this species, and the record explicitly excludes its winter/spring spawning aggregation from any targeting cue, so no season-keyed rule is written.", reviewedAt: REVIEWED_AT },
  { speciesId: "mycteroperca_phenax", mode: "no_reviewed_rule", note: "No condition in the reviewed record moves scamp off the generic model. Feeding strategy is recorded as ambush/opportunistic only (no pursuit mode, unlike the closely related gag), no tide, light, or thermal claim is sourced, and the species' actually-preferred low-relief live-bottom habitat has no matching holding class in the reviewed vocabulary, so no rule can be tied to it.", reviewedAt: REVIEWED_AT },
  { speciesId: "ophiodon_elongatus", mode: "weighted", note: "Lingcod weighting expresses two documented mechanics: current concentrating prey near the ambush point (tide movement), and active off-bottom piscivory when fish forage is verified offshore. The record's nest-guarding-male exception is deliberately kept out of any rule.", reviewedAt: REVIEWED_AT },
  { speciesId: "paralichthys_dentatus", mode: "no_reviewed_rule", note: "Summer flounder genuinely support no weighting rule. The only tide-specific finding is a young-of-year, single-region creek-entry study the record itself declines to generalize to adults, the diel signal is flagged as thin and possibly not range-wide, and the one documented forage-triggered behavior shift (chasing bait to the surface) has no reviewed presentation family that represents it for this species.", reviewedAt: REVIEWED_AT },
  { speciesId: "pogonias_cromis", mode: "no_reviewed_rule", note: "Black drum genuinely support no weighting rule. The record explicitly states no tide-stage relationship was sourced despite the species being fished on tidal marsh and oyster habitat, and no diel, clarity, or forage-conditional behavior was documented beyond generalist bottom-crushing that the baseline family list already covers.", reviewedAt: REVIEWED_AT },
  { speciesId: "pomatomus_saltatrix", mode: "weighted", note: "Bluefish weighting is forage-triggered rather than tide-triggered: the record found no tide-stage relationship, but it does document the surface 'blitz' on schooled bait at the current-compressed edges anglers already fish.", reviewedAt: REVIEWED_AT },
  { speciesId: "rachycentron_canadum", mode: "weighted", note: "Cobia's weighting expresses three distinct reviewed relationships to water -- inshore sight-fishing on the spring migration, nearshore fixed-object holding, and offshore current-formed structure -- each restricted to the water type and family set it is actually reviewed for.", reviewedAt: REVIEWED_AT },
  { speciesId: "rhizoprionodon_terraenovae", mode: "weighted", note: "Atlantic sharpnose has the fullest dossier of the four sharks in this batch -- identification, behavior, diet, and seasonal calendar are all status: reviewed -- and its NOAA-sourced inshore/offshore seasonal migration maps cleanly onto the species' reviewed water types.", reviewedAt: REVIEWED_AT },
  { speciesId: "sciaenops_ocellatus", mode: "weighted", note: "Red drum weighting expresses the estuary's clearest tide signal: subadults hold at structured low-tide sites and disperse across the flooded marsh on the flood, with light modifying rather than overriding that response.", reviewedAt: REVIEWED_AT },
  { speciesId: "scomberomorus_cavalla", mode: "weighted", note: "King mackerel's weighting separates its two reviewed water types by what draws it there: nearshore bait concentrations versus offshore current-formed features.", reviewedAt: REVIEWED_AT },
  { speciesId: "scomberomorus_maculatus", mode: "weighted", note: "Spanish mackerel weighting reflects a genuine moving-water claim in the record: current, not tide direction, is what compresses bait against the edges this species is reviewed for.", reviewedAt: REVIEWED_AT },
  { speciesId: "sebastes_brevispinis", mode: "no_reviewed_rule", note: "Silvergray rockfish is the thinnest-sourced species in this batch: the diet dossier is empty by design (no species-specific source found), feeding strategy is an explicit unconfirmed placeholder, water-column position (pelagic schooler vs. bottom aggregator) is contradicted between agency sources and left unresolved, and no tide, light, thermal, or seasonal shift is documented. There is nothing reviewed to hang a rule on.", reviewedAt: REVIEWED_AT },
  { speciesId: "sebastes_maliger", mode: "weighted", note: "Quillback rockfish weighting expresses the one mechanic the record singles out specifically for this species (not shared with the other rockfish reviewed alongside it): hard, complex substrate with vertical relief is described as a habitat requirement, not just a preference, for a solitary, crevice-sheltering fish.", reviewedAt: REVIEWED_AT },
  { speciesId: "sebastes_miniatus", mode: "no_reviewed_rule", note: "Vermilion rockfish's reviewed record does not distinguish it from generic sedentary-reef-rockfish behavior already covered by the water-type/depth split: no tide, light, or thermal claim is sourced, feeding is ambush/opportunistic with no pursuit mode, and coverUse is generic reef-system site fidelity without the more specific vertical-relief/crevice language that justifies a rule for quillback rockfish. Rather than duplicate that rule on a thinner basis, this species is left unweighted.", reviewedAt: REVIEWED_AT },
  { speciesId: "sebastes_variabilis", mode: "weighted", note: "Dusky rockfish weighting expresses the one trait that clearly separates it from the other rockfish reviewed in this batch: it is classified as a pelagic, mid-water schooling rockfish rather than a solitary bottom-hugger, with a diet almost entirely krill and sand lance.", reviewedAt: REVIEWED_AT },
  { speciesId: "seriola_dumerili", mode: "no_reviewed_rule", note: "No thermal band, no current-facing or light-response account, and a seasonal calendar the record itself says 'largely repeat[s] the year-round structure-use pattern' leave nothing to condition a delta on beyond the life-stage split (pelagic juvenile vs. structure-holding adult) the scenario inputs cannot express.", reviewedAt: REVIEWED_AT },
  { speciesId: "sphyrna_tiburo", mode: "no_reviewed_rule", note: "The record is dominated by identification and a lengthy regulatory caveat, including a global IUCN Endangered reassessment the domestic 'unknown' stock status has not caught up with; the mechanical record behind that caveat is thin (no thermal, current-facing, or light data, and a seasonal calendar with only two overlapping partial entries), so no delta is written pending that unresolved conservation flag.", reviewedAt: REVIEWED_AT },
  { speciesId: "tautoga_onitis", mode: "weighted", note: "Tautog weighting expresses the one clearly documented mechanic: a bottom-temperature-triggered shift between shallow, complex structure in warm months and deeper, more rugged structure once the fall trigger is crossed. Its strongly diurnal light response and its tide-independent, cover-only current preference are both explicitly stated but leave no family, within the already-passive reviewed set, to move against, so neither becomes a rule.", reviewedAt: REVIEWED_AT },
  { speciesId: "thunnus_albacares", mode: "weighted", note: "Yellowfin's weighting distinguishes working a located current front from working a visible bait school, both drawn from peer-reviewed tagging and habitat-suitability work.", reviewedAt: REVIEWED_AT },
  { speciesId: "trachinotus_falcatus", mode: "no_reviewed_rule", note: "Permit genuinely support no weighting rule. The reviewed record names its own largest gap as tide-stage behavior on the flats, and no diel, thermal, or forage-conditional signal was sourced either, so nothing here is well-grounded enough to turn into a delta.", reviewedAt: REVIEWED_AT },
];

export const SPECIES_WEIGHT_OVERRIDES_MARINE: SpeciesWeightOverrideRule[] = [
  {
    id: "bonefish-flood-access",
    speciesId: "albula_vulpes",
    when: { waterTypes: ["inshore"], holding: ["tidal_creek", "creek_mouth", "grass_flat", "sand_hole"], tideMovements: ["flooding"] },
    bias: { flats_sight_cast: 8, tidal_drift_bait: 5 },
    note: "Acoustic telemetry found bonefish essentially absent from shallow creek backwaters at low water, entering only as depth rose after low tide and peaking in detections roughly four hours later, so a rising tide is what makes this shallow foraging ground reachable at all, not a preferred feeding stage layered on top of access that already exists.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "bonefish-low-water-absence",
    speciesId: "albula_vulpes",
    when: { waterTypes: ["inshore"], holding: ["tidal_creek", "creek_mouth", "grass_flat", "sand_hole"], tideMovements: ["slack_low"] },
    bias: { flats_sight_cast: -5, tidal_drift_bait: -4 },
    note: "The same telemetry recorded near-zero detections in these shallow creek backwaters around low water. There is not enough water over the bottom for the fish to be using it, so presentations built around fish holding on this ground should be discounted at low slack rather than simply fished more quietly.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "bonefish-night-inactive",
    speciesId: "albula_vulpes",
    when: { waterTypes: ["inshore"], holding: ["tidal_creek", "creek_mouth", "grass_flat", "sand_hole"], light: ["night"] },
    bias: { flats_sight_cast: -5, tidal_drift_bait: -4, live_natural_bait_suspension: -3 },
    note: "The same telemetry study recorded roughly seven daytime detections in these creek backwaters for every one at night, so darkness is not just a sight-casting problem for this species on this ground; the fish are mostly not foraging there at all after dark.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "white-seabass-winter-deep-structure",
    speciesId: "atractoscion_nobilis",
    when: { waterTypes: ["nearshore"], seasons: ["winter"], holding: ["kelp_edge", "nearshore_reef", "rock_pile"] },
    bias: { structure_vertical: 7, live_bait_slow_troll: -4 },
    note: "Telemetry found white seabass sitting deeper in the water column from October through March than in the warmer months, so a presentation that holds in the column over structure fits that winter depth band better than a near-surface trolled approach.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "white-seabass-summer-shallow-kelp",
    speciesId: "atractoscion_nobilis",
    when: { waterTypes: ["nearshore"], seasons: ["summer", "early_summer"], holding: ["kelp_edge"] },
    bias: { live_bait_slow_troll: 7, structure_vertical: 4 },
    note: "The same telemetry study found white seabass shallowest and most surface-oriented in the warmer months, peaking in July, so a presentation worked near the surface along the kelp edge fits that seasonal shift better than a deep vertical approach.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "spinner-shark-surf-baitfish-pursuit",
    speciesId: "carcharhinus_brevipinna",
    when: { waterTypes: ["surf"], forage: ["small_forage_fish"] },
    bias: { run_and_gun_cast: 6, surf_bait_soak: -4 },
    note: "Spinner sharks are named for leaping while driving through baitfish schools, a pursuit behavior on visible surface activity rather than a wait-and-scent style of feeding, so a still bottom soak is a worse match than casting to the activity when forage fish are actually present.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "blacktip-winter-cold-water-drift",
    speciesId: "carcharhinus_limbatus",
    when: { waterTypes: ["inshore", "nearshore"], seasons: ["winter"] },
    bias: { chum_established_drift: 7, live_bait_slow_troll: 6 },
    note: "Peer-reviewed aerial survey work found blacktip aggregation density peaking in nearshore water below about 77°F in winter, so working a moving, loosely grouped population with a maintained scent trail or slow-trolled live bait fits better than a single fixed-station soak.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "blacktip-surf-baitfish-pursuit",
    speciesId: "carcharhinus_limbatus",
    when: { waterTypes: ["surf"], forage: ["small_forage_fish"] },
    bias: { run_and_gun_cast: 6 },
    note: "Blacktips are an opportunistic pursuit predator on schooling baitfish and vessel discards rather than an ambush feeder from cover, so casting to visible surface activity fits the reviewed feeding pattern when forage fish are actually present in the surf zone.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "snook-moving-tide-ambush",
    speciesId: "centropomus_undecimalis",
    when: { waterTypes: ["inshore"], holding: ["mangrove_edge", "tidal_creek", "creek_mouth", "channel_edge"], tideMovements: ["flooding", "ebbing"] },
    bias: { structure_pitch: 7, tidal_drift_bait: 6, live_natural_bait_suspension: 4, horizontal_retrieve: -3 },
    note: "FWC describes snook as conservative ambush predators that orient to face moving water and let it deliver food past them, which favors working a bait or lure past structure the current is running along rather than searching for the fish. The rule fires on either tide direction rather than one specifically, because no source resolved the behavior to flood versus ebb.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "black-sea-bass-cold-refuge-shelter",
    speciesId: "centropristis_striata",
    when: { waterTypes: ["nearshore"], thermalStates: ["cold_refuge"] },
    bias: { structure_vertical: 7, drop_presentation: 5, bottom_contact: -4 },
    note: "Near the cold end of this species' range, sourced material describes fish becoming inactive and sheltering in holes and crevices rather than ranging to feed, so presentations that hold tight in the water column right over structure outrank ones that search adjacent open bottom.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "black-sea-bass-nearshore-bright-structure",
    speciesId: "centropristis_striata",
    when: { waterTypes: ["nearshore"], light: ["bright"] },
    bias: { structure_vertical: 5, drop_presentation: 4 },
    note: "In bright light this species shelters in and around hard structure, so a presentation held directly over or dropped into structure fits better than one worked across open bottom.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "black-sea-bass-nearshore-lowlight-range",
    speciesId: "centropristis_striata",
    when: { waterTypes: ["nearshore"], light: ["low_light"] },
    bias: { bottom_contact: 6, live_natural_bait_suspension: 4 },
    note: "As light drops, black sea bass extend their foraging onto the adjacent open/soft bottom rather than staying tucked to structure, favoring presentations that cover or hold over that adjacent bottom.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "black-sea-bass-inshore-bright-structure",
    speciesId: "centropristis_striata",
    when: { waterTypes: ["inshore"], light: ["bright"] },
    bias: { structure_pitch: 6 },
    note: "The same bright-light structure-holding pattern applies inshore: a bait pitched tight to oyster bar, piling, or channel-edge structure fits better than one left to sit off the structure.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "black-sea-bass-inshore-lowlight-range",
    speciesId: "centropristis_striata",
    when: { waterTypes: ["inshore"], light: ["low_light"] },
    bias: { live_natural_bait_suspension: 6 },
    note: "As light drops and fish range off structure to feed on adjacent bottom, a held natural bait covering the water near (not only on) the structure fits the documented shift better than a tight structure pitch alone.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "mahi-weedline-current-search",
    speciesId: "coryphaena_hippurus",
    when: { waterTypes: ["offshore"], holding: ["weed_line", "current_rip", "temperature_break"] },
    bias: { run_and_gun_cast: 7, trolling_spread: 6 },
    note: "Mahi-mahi concentrate under drifting Sargassum and along current-driven fronts because those features aggregate its prey, so presentations built to find and cast to that visible activity outrank ones that do not.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "mahi-daytime-surface-pursuit",
    speciesId: "coryphaena_hippurus",
    when: { waterTypes: ["offshore"], light: ["bright", "mixed"] },
    bias: { run_and_gun_cast: 6 },
    note: "Mahi-mahi are a documented daytime surface feeder that dives deeper by day beneath structure and stays shallow at night, so casting to visible surface activity is a daylight-favored tactic.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "mahi-located-weedline-school",
    speciesId: "coryphaena_hippurus",
    when: { waterTypes: ["offshore"], holding: ["weed_line"] },
    bias: { chum_established_drift: 6, live_bait_slow_troll: 5 },
    note: "Once a school is found holding under a weed line, mahi-mahi's floating-structure association is strong enough to hold fish in place for a scent trail or slow-trolled bait rather than requiring continued searching.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "seatrout-day-grass-suspension",
    speciesId: "cynoscion_nebulosus",
    when: { waterTypes: ["inshore"], holding: ["grass_flat"], light: ["bright", "mixed"] },
    bias: { live_natural_bait_suspension: 6, tidal_drift_bait: 4, horizontal_retrieve: -4 },
    note: "Telemetry found spotted seatrout over seagrass 98 percent of the time in daylight, moving at under a meter a minute, so daylight favors a bait held or worked slowly through the grass over a retrieve built to search open water for a fish that is not covering much ground.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "seatrout-night-open-bottom-search",
    speciesId: "cynoscion_nebulosus",
    when: { waterTypes: ["inshore"], holding: ["sand_hole", "channel_edge"], light: ["night", "low_light"] },
    bias: { horizontal_retrieve: 7, stop_and_go: 6, live_natural_bait_suspension: -3 },
    note: "The same telemetry has trout leaving seagrass for bare substrate at night while moving at nearly four times the daytime rate, so low light favors a moving search presentation over open bottom rather than a bait parked in one place.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "weakfish-dusk-dawn-grass-edge",
    speciesId: "cynoscion_regalis",
    when: { waterTypes: ["inshore"], holding: ["grass_flat"], light: ["low_light", "night"] },
    bias: { tidal_drift_bait: 7, live_natural_bait_suspension: 6 },
    note: "A federal biological report states weakfish feed primarily between dusk and dawn while foraging along the edge of eelgrass beds, so low light at a grass edge is the window this species is actually built to feed in.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "weakfish-bright-daylight-lull",
    speciesId: "cynoscion_regalis",
    when: { waterTypes: ["inshore"], holding: ["grass_flat"], light: ["bright"] },
    bias: { tidal_drift_bait: -4, live_natural_bait_suspension: -3 },
    note: "Since the same source ties weakfish feeding primarily to the dusk-to-dawn window, full daylight at the same grass edge is comparatively the weaker part of the cycle for the two presentations built around an active bite there.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "halibut-nearshore-pelagic-pursuit",
    speciesId: "hippoglossus_stenolepis",
    when: { waterTypes: ["nearshore"], forage: ["small_forage_fish"] },
    bias: { vertical_jig: 8 },
    note: "When baitfish such as herring or sand lance are actually being observed, halibut are documented to actively leave the bottom to intercept them, so a presentation worked up through the column outranks one left flat on bottom.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "halibut-offshore-pelagic-pursuit",
    speciesId: "hippoglossus_stenolepis",
    when: { waterTypes: ["offshore"], forage: ["small_forage_fish"] },
    bias: { vertical_jig: 7, deep_drop: -3 },
    note: "The same off-bottom pursuit behavior applies offshore: verified baitfish forage favors a worked mid-column presentation over one parked on the bottom.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "striped-marlin-frontal-zone-search",
    speciesId: "kajikia_audax",
    when: { waterTypes: ["offshore"], holding: ["temperature_break", "current_rip"] },
    bias: { trolling_spread: 7, live_bait_slow_troll: 6, chum_established_drift: 4 },
    note: "Striped marlin concentrate at frontal zones where cooler and warmer water meet because those fronts concentrate the baitfish and squid it hunts visually, so presentations that cover or work that seam outrank ones that do not.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "striped-marlin-daytime-visual-hunt",
    speciesId: "kajikia_audax",
    when: { waterTypes: ["offshore"], light: ["bright", "mixed"] },
    bias: { trolling_spread: 6, live_bait_slow_troll: 5 },
    note: "This is a visual, pursuit-hunting predator described as diurnal, with reduced movement documented at night, so daylight favors moving presentations a fish can see and chase.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "striped-marlin-low-light-caution",
    speciesId: "kajikia_audax",
    when: { waterTypes: ["offshore"], light: ["low_light", "night"] },
    bias: { trolling_spread: -4, live_bait_slow_troll: -3 },
    note: "The same telemetry finding of reduced nocturnal horizontal movement argues against weighting active, wide-searching presentations as heavily once light drops, since a visual hunter covering less ground is less likely to encounter them.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "mutton-snapper-inshore-current-delivery",
    speciesId: "lutjanus_analis",
    when: { waterTypes: ["inshore"], holding: ["mangrove_edge"], tideMovements: ["flooding", "ebbing"] },
    bias: { tidal_drift_bait: 6, structure_pitch: 4 },
    note: "Mutton snapper hold tight to structure and rely on current to sweep prey past it rather than actively working open tide lines, so on a moving tide a bait let to travel at tide speed along the mangrove edge fits the documented mechanic better than a stationary presentation off the structure.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "mutton-snapper-nearshore-current-delivery",
    speciesId: "lutjanus_analis",
    when: { waterTypes: ["nearshore"], tideMovements: ["flooding", "ebbing"] },
    bias: { bottom_contact: 5, structure_vertical: 3 },
    note: "The same current-delivers-prey-past-structure mechanic applies on nearshore reef and hardbottom: moving water favors a presentation worked along or held over structure rather than one that ignores current direction.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "gag-nearshore-baitfish-pursuit",
    speciesId: "mycteroperca_microlepis",
    when: { waterTypes: ["nearshore"], forage: ["small_forage_fish", "larger_prey_fish"] },
    bias: { vertical_jig: 7, live_natural_bait_suspension: 4, bottom_contact: -3 },
    note: "Gag are described as ambushing from structure and actively pursuing schooling baitfish and other reef fish, not just picking the bottom, so when fish forage is actually present a worked or held presentation in the column outranks a bottom search.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "gag-offshore-baitfish-pursuit",
    speciesId: "mycteroperca_microlepis",
    when: { waterTypes: ["offshore"], forage: ["small_forage_fish", "larger_prey_fish"] },
    bias: { live_bait_slow_troll: 8, vertical_jig: 6, chum_established_drift: 4, deep_drop: -3 },
    note: "The same documented pursuit behavior favors a naturally swimming or actively worked presentation over a bait parked on bottom when fish forage is verified offshore.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "lingcod-nearshore-moving-tide-ambush",
    speciesId: "ophiodon_elongatus",
    when: { waterTypes: ["nearshore"], tideMovements: ["flooding", "ebbing"] },
    bias: { vertical_jig: 6, structure_vertical: 5 },
    note: "Moving water is documented to concentrate the small fish, squid, and crab lingcod ambush from cover, so a presentation actively worked in the column right over structure has more to compete against and stand out from than a static bait would.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "lingcod-nearshore-slack-static-ambush",
    speciesId: "ophiodon_elongatus",
    when: { waterTypes: ["nearshore"], tideMovements: ["slack_high", "slack_low"] },
    bias: { drop_presentation: 5, bottom_contact: 4 },
    note: "Without moving water to concentrate prey past the ambush point, a bait placed and held directly in the lie fits this structure-bound ambush predator better than an actively worked presentation.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "lingcod-offshore-piscivory",
    speciesId: "ophiodon_elongatus",
    when: { waterTypes: ["offshore"], forage: ["small_forage_fish", "larger_prey_fish"] },
    bias: { trolling: 8, vertical_jig: 5, deep_drop: -3 },
    note: "Adults are documented as heavily fish-eating, with fish making up most of stomach volume in larger individuals, so when fish forage is verified a presentation that covers water or works the column outranks one anchored to the bottom.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "bluefish-surf-blitz-forage",
    speciesId: "pomatomus_saltatrix",
    when: { waterTypes: ["surf"], holding: ["rip_channel", "outer_sandbar"], forage: ["small_forage_fish"] },
    bias: { run_and_gun_cast: 8, surf_metal_cast: 5 },
    note: "Bluefish are documented schooling pursuit predators whose best-known feeding pattern is a surface 'blitz' on schooled baitfish. When small forage fish are actually present at a rip or bar where moving water concentrates them, that favors casting to visible surface activity over a slower presentation built for a fish holding still.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "bluefish-inlet-blitz-forage",
    speciesId: "pomatomus_saltatrix",
    when: { waterTypes: ["nearshore"], holding: ["inlet_mouth"], forage: ["small_forage_fish"] },
    bias: { run_and_gun_cast: 8, bottom_contact: -4 },
    note: "The same blitz behavior and the agency statement that anglers find bluefish concentrated at inlets, shoals and rips extends to inlet mouths. When small forage fish are actually present there, that favors casting to a moving surface school over a slow bottom presentation built for a fish that is not schooling pelagically.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "cobia-spring-inshore-migration-sight",
    speciesId: "rachycentron_canadum",
    when: { waterTypes: ["inshore"], seasons: ["spring"] },
    bias: { flats_sight_cast: 8, run_and_gun_cast: 6, structure_pitch: 4 },
    note: "Cobia's spring push is a near-surface, sight-fished migration along the beachfront and into inshore water, so presentations built around spotting a cruising fish and casting to it, or working the bridges and channel edges it migrates past, fit better than a blind soak.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "cobia-nearshore-fixed-structure",
    speciesId: "rachycentron_canadum",
    when: { waterTypes: ["nearshore"], holding: ["wreck", "artificial_reef"] },
    bias: { structure_vertical: 7, live_bait_slow_troll: 4 },
    note: "Cobia are strongly object-oriented, holding tight to buoys, wrecks, and artificial reefs rather than working open water, so a presentation that stays in the column directly over that structure fits its documented behavior.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "cobia-offshore-current-structure",
    speciesId: "rachycentron_canadum",
    when: { waterTypes: ["offshore"], holding: ["weed_line", "current_rip"] },
    bias: { tide_line_drift: 7, live_bait_slow_troll: 5 },
    note: "Offshore, cobia use current-formed features -- weed lines and rips -- while moving rather than holding a fixed lie, so working the visible seam or slow-trolling live bait along it fits better than a stationary approach.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "sharpnose-winter-nearshore-bottom",
    speciesId: "rhizoprionodon_terraenovae",
    when: { waterTypes: ["nearshore"], seasons: ["winter"] },
    bias: { bottom_contact: 7 },
    note: "NOAA describes this species moving out of inshore bays and surf zones into deeper offshore water in winter, so within the water types this catalog covers, a bottom-oriented nearshore presentation fits that posture better than a mid-water or surf approach.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "sharpnose-warm-season-inshore-return",
    speciesId: "rhizoprionodon_terraenovae",
    when: { waterTypes: ["inshore"], seasons: ["spring", "early_summer", "summer"] },
    bias: { tidal_drift_bait: 6, live_natural_bait_suspension: 5 },
    note: "NOAA describes this species returning to inshore bays, estuaries, and creek mouths from spring through summer, matching its small bottom/mid-water opportunistic feeding style to bait presentations that work an edge or hold a station in that water.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "sharpnose-warm-season-surf",
    speciesId: "rhizoprionodon_terraenovae",
    when: { waterTypes: ["surf"], seasons: ["spring", "early_summer", "summer"] },
    bias: { surf_bait_soak: 6 },
    note: "The same spring-through-summer inshore return puts this species in surf-zone habitat over mud and sand, where a bait held on the bottom fits its benthic and small-fish diet better than active surf presentations.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "red-drum-oyster-ebb-concentration",
    speciesId: "sciaenops_ocellatus",
    when: { waterTypes: ["inshore"], holding: ["marsh_edge", "oyster_bar", "creek_mouth"], tideMovements: ["ebbing"] },
    bias: { structure_pitch: 8, tidal_drift_bait: 5, flats_sight_cast: -4 },
    note: "Telemetry found subadult red drum showing high site fidelity to a structured low-tide site carrying overhead structure and adjacent oyster reef, with predictable dispersal only once the flood begins, so a falling tide concentrates fish at structure rather than spreading them across open water, and working that structure outperforms searching open grass for a sighted fish.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "red-drum-flood-marsh-dispersal",
    speciesId: "sciaenops_ocellatus",
    when: { waterTypes: ["inshore"], holding: ["marsh_edge", "grass_flat", "tidal_creek"], tideMovements: ["flooding"], light: ["bright", "mixed"] },
    bias: { flats_sight_cast: 8, tidal_drift_bait: 4, structure_pitch: -4 },
    note: "The same telemetry has fish dispersing off the low-tide structure and onto the flooded marsh surface and through intertidal channels once the tide turns, and agency accounts separately document visible daytime tailing over shallow grass, so a daylight flood favors sight-casting to fish spread across open water over working the structure they have just left.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "red-drum-night-flood-holds",
    speciesId: "sciaenops_ocellatus",
    when: { waterTypes: ["inshore"], holding: ["marsh_edge", "oyster_bar", "creek_mouth"], tideMovements: ["flooding"], light: ["night"] },
    bias: { structure_pitch: 6, live_natural_bait_suspension: 4, flats_sight_cast: -5 },
    note: "The same telemetry study found that subadults which normally disperse onto the flooded marsh on a daytime flood stayed put at their low-tide structured site when the flood began after sunset, so a flooding tide after dark should not be read as the same dispersal cue it is in daylight.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "king-mackerel-nearshore-bait-schools",
    speciesId: "scomberomorus_cavalla",
    when: { waterTypes: ["nearshore"], forage: ["small_forage_fish"] },
    bias: { live_bait_slow_troll: 8, trolling: 5 },
    note: "King mackerel is a voracious pursuit predator on schooling baitfish and is not strongly structure-dependent, so when forage fish are actually present nearshore, presentations that cover water near the bait outperform sitting over a fixed piece of structure.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "king-mackerel-offshore-temperature-break",
    speciesId: "scomberomorus_cavalla",
    when: { waterTypes: ["offshore"], holding: ["temperature_break", "current_rip"] },
    bias: { tide_line_drift: 8, trolling_spread: 5 },
    note: "Offshore, king mackerel concentrate along temperature breaks and current rips where bait collects rather than at fixed structure, so working the visible seam or spreading trolled baits across it fits its documented current-edge association.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "spanish-mackerel-moving-tide-compression-surf",
    speciesId: "scomberomorus_maculatus",
    when: { waterTypes: ["surf"], holding: ["rip_channel", "jetty_wash"], tideMovements: ["flooding", "ebbing"] },
    bias: { run_and_gun_cast: 7, surf_metal_cast: 5 },
    note: "Spanish mackerel are described as concentrating where tide-driven current compresses baitfish against a beach cut, jetty, inlet mouth or reef edge rather than holding a fixed lie, so moving water at a rip or jetty is what creates the bait concentration this species is built to exploit. The rule does not fire on slack water, when that compression mechanism is absent.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "spanish-mackerel-moving-tide-compression-nearshore",
    speciesId: "scomberomorus_maculatus",
    when: { waterTypes: ["nearshore"], holding: ["inlet_mouth"], tideMovements: ["flooding", "ebbing"] },
    bias: { run_and_gun_cast: 7, live_bait_slow_troll: 4 },
    note: "The same current-compression mechanism applies at an inlet mouth: moving tide concentrates baitfish there, favoring a presentation cast or trolled to intercept the school over one built for still water.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "quillback-nearshore-crevice-structure",
    speciesId: "sebastes_maliger",
    when: { waterTypes: ["nearshore"] },
    bias: { drop_presentation: 6, structure_vertical: 6, bottom_contact: -3 },
    note: "Quillback are described as solitary reef-dwellers perched on rocks or sheltering in crevices and holes on structure with vertical relief, so a presentation dropped or held tight into that structure fits better than one worked broadly across open bottom.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "quillback-offshore-crevice-structure",
    speciesId: "sebastes_maliger",
    when: { waterTypes: ["offshore"] },
    bias: { deep_drop: 5, trolling: -3 },
    note: "The same vertical-relief, site-fixed crevice-holding pattern favors a presentation placed and held on structure over one that covers open water searching for fish.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "dusky-rockfish-offshore-pelagic-column",
    speciesId: "sebastes_variabilis",
    when: { waterTypes: ["offshore"] },
    bias: { suspended_stationary: 8, vertical_jig: 5, deep_drop: -4 },
    note: "Dusky rockfish are classed as a pelagic, mid-water schooling species with a diet almost entirely krill and sand lance, so a presentation held or worked in the water column at the fish's depth band outranks one anchored to the bottom.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "tautog-nearshore-fall-deeper-structure",
    speciesId: "tautoga_onitis",
    when: { seasons: ["fall"], waterTypes: ["nearshore"] },
    bias: { structure_vertical: 6, bottom_contact: 5, drop_presentation: -3 },
    note: "As bottom temperature drops below the documented fall migration trigger, tautog move off shallow structure onto deeper, more rugged bottom, so working the column tight over that deeper relief and dragging bottom fit better than a shallow-water pitch-and-drop into structure.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "tautog-nearshore-summer-shallow-structure",
    speciesId: "tautoga_onitis",
    when: { seasons: ["summer"], waterTypes: ["nearshore"] },
    bias: { drop_presentation: 6, bottom_contact: 3 },
    note: "In the warm months tautog and juveniles share shallow, crevice-scale structure, and the reviewed summer presentation set adds a dropped presentation into that structure that the fall entry drops in favor of deeper vertical work.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "yellowfin-current-front",
    speciesId: "thunnus_albacares",
    when: { waterTypes: ["offshore"], holding: ["temperature_break", "current_rip"] },
    bias: { chum_established_drift: 7, live_bait_slow_troll: 6, trolling_spread: 4 },
    note: "Yellowfin habitat suitability is highest at mesoscale current fronts and eddy margins where convergence concentrates prey, so once a boat is on that seam, holding a scent trail or slow-trolled bait there fits better than continuing to search.",
    reviewedAt: REVIEWED_AT,
  },
  {
    id: "yellowfin-bait-school-depth-band",
    speciesId: "thunnus_albacares",
    when: { waterTypes: ["offshore"], holding: ["open_bait_school"] },
    bias: { vertical_jig: 7, live_bait_slow_troll: 5 },
    note: "Tagged yellowfin track the vertical migration of the deep scattering layer both day and night, feeding on that same prey band, so working a marked bait concentration through its depth fits better than a family with no depth control.",
    reviewedAt: REVIEWED_AT,
  },
];

export function matchingSpeciesWeightOverrideMarine(
  input: ScenarioInput,
  thermalState: ThermalState,
): SpeciesWeightOverrideRule[] {
  return SPECIES_WEIGHT_OVERRIDES_MARINE.filter((rule) =>
    matchesOverrideRule(rule, input, thermalState),
  );
}
