import { useEffect } from "react";
import { registerSW } from "virtual:pwa-register";

/**
 * Registers the Workbox service worker generated by vite-plugin-pwa, so
 * reviewed records stay readable when the radio drops. The web manifest is
 * first-party and static at `public/manifest.webmanifest`.
 */
export function PwaRegister() {
  useEffect(() => {
    registerSW({ immediate: true });
  }, []);
  return null;
}
