import { useEffect } from "react";
import { registerSW } from "virtual:pwa-register";

/**
 * Registers the Workbox service worker generated by vite-plugin-pwa.
 * Grok still owns the web manifest and the ?install=1 tutorial; this only
 * claims the page so reviewed records stay available when the radio drops.
 */
export function PwaRegister() {
  useEffect(() => {
    registerSW({ immediate: true });
  }, []);
  return null;
}
