/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoundaryRouteImport } from './routes/boundary'
import { Route as ApiDossierCoverageRouteImport } from './routes/api/dossier-coverage'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as SpeciesIndexRouteImport } from './routes/species.index'
import { Route as SpeciesSpeciesIdRouteImport } from './routes/species.$speciesId'
import { Route as ApiDossiersSpeciesIdRouteImport } from './routes/api/dossiers.$speciesId'
import { Route as ApiWaterContextSpeciesIdRouteImport } from './routes/api/water-context.$speciesId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoundaryRoute = BoundaryRouteImport.update({
  id: '/boundary',
  path: '/boundary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDossierCoverageRoute = ApiDossierCoverageRouteImport.update({
  id: '/api/dossier-coverage',
  path: '/api/dossier-coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesIndexRoute = SpeciesIndexRouteImport.update({
  id: '/species/',
  path: '/species/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesSpeciesIdRoute = SpeciesSpeciesIdRouteImport.update({
  id: '/species/$speciesId',
  path: '/species/$speciesId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDossiersSpeciesIdRoute = ApiDossiersSpeciesIdRouteImport.update({
  id: '/api/dossiers/$speciesId',
  path: '/api/dossiers/$speciesId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaterContextSpeciesIdRoute =
  ApiWaterContextSpeciesIdRouteImport.update({
    id: '/api/water-context/$speciesId',
    path: '/api/water-context/$speciesId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boundary': typeof BoundaryRoute
  '/api/dossier-coverage': typeof ApiDossierCoverageRoute
  '/api/health': typeof ApiHealthRoute
  '/api/version': typeof ApiVersionRoute
  '/species/$speciesId': typeof SpeciesSpeciesIdRoute
  '/species/': typeof SpeciesIndexRoute
  '/api/dossiers/$speciesId': typeof ApiDossiersSpeciesIdRoute
  '/api/water-context/$speciesId': typeof ApiWaterContextSpeciesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boundary': typeof BoundaryRoute
  '/api/dossier-coverage': typeof ApiDossierCoverageRoute
  '/api/health': typeof ApiHealthRoute
  '/api/version': typeof ApiVersionRoute
  '/species/$speciesId': typeof SpeciesSpeciesIdRoute
  '/species': typeof SpeciesIndexRoute
  '/api/dossiers/$speciesId': typeof ApiDossiersSpeciesIdRoute
  '/api/water-context/$speciesId': typeof ApiWaterContextSpeciesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boundary': typeof BoundaryRoute
  '/api/dossier-coverage': typeof ApiDossierCoverageRoute
  '/api/health': typeof ApiHealthRoute
  '/api/version': typeof ApiVersionRoute
  '/species/$speciesId': typeof SpeciesSpeciesIdRoute
  '/species/': typeof SpeciesIndexRoute
  '/api/dossiers/$speciesId': typeof ApiDossiersSpeciesIdRoute
  '/api/water-context/$speciesId': typeof ApiWaterContextSpeciesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boundary'
    | '/api/dossier-coverage'
    | '/api/health'
    | '/api/version'
    | '/species/$speciesId'
    | '/species/'
    | '/api/dossiers/$speciesId'
    | '/api/water-context/$speciesId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boundary'
    | '/api/dossier-coverage'
    | '/api/health'
    | '/api/version'
    | '/species/$speciesId'
    | '/species'
    | '/api/dossiers/$speciesId'
    | '/api/water-context/$speciesId'
  id:
    | '__root__'
    | '/'
    | '/boundary'
    | '/api/dossier-coverage'
    | '/api/health'
    | '/api/version'
    | '/species/$speciesId'
    | '/species/'
    | '/api/dossiers/$speciesId'
    | '/api/water-context/$speciesId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoundaryRoute: typeof BoundaryRoute
  ApiDossierCoverageRoute: typeof ApiDossierCoverageRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiVersionRoute: typeof ApiVersionRoute
  SpeciesSpeciesIdRoute: typeof SpeciesSpeciesIdRoute
  SpeciesIndexRoute: typeof SpeciesIndexRoute
  ApiDossiersSpeciesIdRoute: typeof ApiDossiersSpeciesIdRoute
  ApiWaterContextSpeciesIdRoute: typeof ApiWaterContextSpeciesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boundary': {
      id: '/boundary'
      path: '/boundary'
      fullPath: '/boundary'
      preLoaderRoute: typeof BoundaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dossier-coverage': {
      id: '/api/dossier-coverage'
      path: '/api/dossier-coverage'
      fullPath: '/api/dossier-coverage'
      preLoaderRoute: typeof ApiDossierCoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species/': {
      id: '/species/'
      path: '/species'
      fullPath: '/species/'
      preLoaderRoute: typeof SpeciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species/$speciesId': {
      id: '/species/$speciesId'
      path: '/species/$speciesId'
      fullPath: '/species/$speciesId'
      preLoaderRoute: typeof SpeciesSpeciesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dossiers/$speciesId': {
      id: '/api/dossiers/$speciesId'
      path: '/api/dossiers/$speciesId'
      fullPath: '/api/dossiers/$speciesId'
      preLoaderRoute: typeof ApiDossiersSpeciesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/water-context/$speciesId': {
      id: '/api/water-context/$speciesId'
      path: '/api/water-context/$speciesId'
      fullPath: '/api/water-context/$speciesId'
      preLoaderRoute: typeof ApiWaterContextSpeciesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoundaryRoute: BoundaryRoute,
  ApiDossierCoverageRoute: ApiDossierCoverageRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiVersionRoute: ApiVersionRoute,
  SpeciesSpeciesIdRoute: SpeciesSpeciesIdRoute,
  SpeciesIndexRoute: SpeciesIndexRoute,
  ApiDossiersSpeciesIdRoute: ApiDossiersSpeciesIdRoute,
  ApiWaterContextSpeciesIdRoute: ApiWaterContextSpeciesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
