/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoundaryRouteImport } from './routes/boundary'
import { Route as ApiDossierCoverageRouteImport } from './routes/api/dossier-coverage'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiDossiersSpeciesIdRouteImport } from './routes/api/dossiers.$speciesId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoundaryRoute = BoundaryRouteImport.update({
  id: '/boundary',
  path: '/boundary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDossierCoverageRoute = ApiDossierCoverageRouteImport.update({
  id: '/api/dossier-coverage',
  path: '/api/dossier-coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDossiersSpeciesIdRoute = ApiDossiersSpeciesIdRouteImport.update({
  id: '/api/dossiers/$speciesId',
  path: '/api/dossiers/$speciesId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boundary': typeof BoundaryRoute
  '/api/dossier-coverage': typeof ApiDossierCoverageRoute
  '/api/health': typeof ApiHealthRoute
  '/api/dossiers/$speciesId': typeof ApiDossiersSpeciesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boundary': typeof BoundaryRoute
  '/api/dossier-coverage': typeof ApiDossierCoverageRoute
  '/api/health': typeof ApiHealthRoute
  '/api/dossiers/$speciesId': typeof ApiDossiersSpeciesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boundary': typeof BoundaryRoute
  '/api/dossier-coverage': typeof ApiDossierCoverageRoute
  '/api/health': typeof ApiHealthRoute
  '/api/dossiers/$speciesId': typeof ApiDossiersSpeciesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boundary'
    | '/api/dossier-coverage'
    | '/api/health'
    | '/api/dossiers/$speciesId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boundary'
    | '/api/dossier-coverage'
    | '/api/health'
    | '/api/dossiers/$speciesId'
  id:
    | '__root__'
    | '/'
    | '/boundary'
    | '/api/dossier-coverage'
    | '/api/health'
    | '/api/dossiers/$speciesId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoundaryRoute: typeof BoundaryRoute
  ApiDossierCoverageRoute: typeof ApiDossierCoverageRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiDossiersSpeciesIdRoute: typeof ApiDossiersSpeciesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boundary': {
      id: '/boundary'
      path: '/boundary'
      fullPath: '/boundary'
      preLoaderRoute: typeof BoundaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dossier-coverage': {
      id: '/api/dossier-coverage'
      path: '/api/dossier-coverage'
      fullPath: '/api/dossier-coverage'
      preLoaderRoute: typeof ApiDossierCoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dossiers/$speciesId': {
      id: '/api/dossiers/$speciesId'
      path: '/api/dossiers/$speciesId'
      fullPath: '/api/dossiers/$speciesId'
      preLoaderRoute: typeof ApiDossiersSpeciesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoundaryRoute: BoundaryRoute,
  ApiDossierCoverageRoute: ApiDossierCoverageRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiDossiersSpeciesIdRoute: ApiDossiersSpeciesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
